import type { VisualTheme, ThemeTypography, ThemeSpacing, ThemeBorderRadius, ThemeShadows } from './types';

/**
 * Tweakcn Theme Library
 *
 * A collection of professionally designed themes inspired by popular color schemes.
 * Based on well-known color palettes: Dracula, Nord, Tokyo Night, Catppuccin, etc.
 *
 * Organized into Dark Themes and Light Themes categories.
 */

// Shared typography settings for all tweakcn themes
const sharedTypography: ThemeTypography = {
  fontFamily: {
    sans: 'var(--font-geist-sans), ui-sans-serif, system-ui, sans-serif',
    mono: 'var(--font-geist-mono), ui-monospace, monospace',
  },
  fontSize: {
    xs: '0.75rem',
    sm: '0.875rem',
    base: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    '5xl': '3rem',
  },
  fontWeight: {
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },
  lineHeight: {
    tight: 1.25,
    normal: 1.5,
    relaxed: 1.75,
  },
  letterSpacing: {
    tight: '-0.02em',
    normal: '0',
    wide: '0.02em',
  },
};

// Shared spacing settings
const sharedSpacing: ThemeSpacing = {
  sidebarWidth: '280px',
  contentPadding: {
    mobile: '1.25rem',
    desktop: '2rem',
  },
  cardGap: '1.5rem',
  sectionMargin: '2rem',
};

// Shared border radius
const sharedBorderRadius: ThemeBorderRadius = {
  sm: '0.5rem',
  md: '0.75rem',
  lg: '1rem',
  xl: '1.25rem',
  full: '9999px',
};

// Shared shadows
const sharedShadows: ThemeShadows = {
  card: '0 2px 4px 0 rgb(0 0 0 / 0.08), 0 1px 2px -1px rgb(0 0 0 / 0.06)',
  elevated: '0 12px 20px -4px rgb(0 0 0 / 0.12), 0 6px 8px -6px rgb(0 0 0 / 0.08)',
  dropdown: '0 24px 32px -8px rgb(0 0 0 / 0.14), 0 12px 16px -8px rgb(0 0 0 / 0.10)',
};

// ==================== DARK THEMES ====================

export const draculaTheme: VisualTheme = {
  id: 'dracula',
  name: 'Dracula',
  description: 'Dark purple theme with vibrant accents',
  category: 'dark',
  light: {
    bg: {
      primary: '#F8F8F2',
      secondary: '#E6E6E0',
      card: '#FFFFFF',
      sidebar: '#44475A',
      elevated: '#FFFFFF',
      hover: '#F0F0EA',
      active: '#E9E9E3',
    },
    text: {
      primary: '#282A36',
      secondary: '#44475A',
      muted: '#6272A4',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#BD93F9',
      secondary: '#FF79C6',
      tertiary: '#8BE9FD',
      hover: '#A681DB',
      active: '#9775C7',
    },
    status: {
      success: '#50FA7B',
      successSubtle: '#EAFEEF',
      warning: '#F1FA8C',
      warningSubtle: '#FDFEF1',
      error: '#FF5555',
      errorSubtle: '#FFEAEA',
      info: '#8BE9FD',
      infoSubtle: '#F1FCFE',
    },
    border: {
      default: '#E0E0DA',
      subtle: '#F0F0EA',
      focus: '#BD93F9',
      hover: '#C9C9C4',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#BD93F9',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#BD93F9',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(40, 42, 54, 0.5)',
      tooltip: '#282A36',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#282A36',
      secondary: '#1E1F29',
      card: '#44475A',
      sidebar: '#191A21',
      elevated: '#44475A',
      hover: '#323440',
      active: '#3D3F4A',
    },
    text: {
      primary: '#F8F8F2',
      secondary: '#BFC9DB',
      muted: '#6272A4',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#BD93F9',
      secondary: '#FF79C6',
      tertiary: '#8BE9FD',
      hover: '#C49FF9',
      active: '#CAA8FA',
    },
    status: {
      success: '#50FA7B',
      successSubtle: '#EAFEEF',
      warning: '#F1FA8C',
      warningSubtle: '#FDFEF1',
      error: '#FF5555',
      errorSubtle: '#FFEAEA',
      info: '#8BE9FD',
      infoSubtle: '#F1FCFE',
    },
    border: {
      default: '#44475A',
      subtle: '#383A46',
      focus: '#BD93F9',
      hover: '#56596A',
    },
    interactive: {
      default: '#323440',
      hover: '#3D3F4A',
      active: '#484954',
      disabled: '#282A36',
      focus: '#BD93F9',
    },
    input: {
      bg: '#44475A',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#BD93F9',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(40, 42, 54, 0.75)',
      tooltip: '#1F2937',
      popover: '#3D3F4A',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#BD93F9', '#FF79C6', '#8BE9FD', '#50FA7B', '#F1FA8C'], positive: '#50FA7B', negative: '#FF5555' },
};

export const nordTheme: VisualTheme = {
  id: 'nord',
  name: 'Nord',
  description: 'Arctic, north-bluish color palette',
  category: 'dark',
  light: {
    bg: {
      primary: '#ECEFF4',
      secondary: '#E5E9F0',
      card: '#FFFFFF',
      sidebar: '#3B4252',
      elevated: '#FFFFFF',
      hover: '#E4E7EC',
      active: '#DDE0E5',
    },
    text: {
      primary: '#2E3440',
      secondary: '#4C566A',
      muted: '#7B88A1',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#5E81AC',
      secondary: '#81A1C1',
      tertiary: '#88C0D0',
      hover: '#527197',
      active: '#4B6789',
    },
    status: {
      success: '#A3BE8C',
      successSubtle: '#F3F7F1',
      warning: '#EBCB8B',
      warningSubtle: '#FCF8F1',
      error: '#BF616A',
      errorSubtle: '#F7ECED',
      info: '#88C0D0',
      infoSubtle: '#F0F7F9',
    },
    border: {
      default: '#D8DEE9',
      subtle: '#E5E9F0',
      focus: '#5E81AC',
      hover: '#C2C7D1',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#5E81AC',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#5E81AC',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(46, 52, 64, 0.5)',
      tooltip: '#2E3440',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#2E3440',
      secondary: '#3B4252',
      card: '#434C5E',
      sidebar: '#242933',
      elevated: '#434C5E',
      hover: '#383E49',
      active: '#424853',
    },
    text: {
      primary: '#ECEFF4',
      secondary: '#D8DEE9',
      muted: '#7B88A1',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#5E81AC',
      secondary: '#81A1C1',
      tertiary: '#88C0D0',
      hover: '#7190B5',
      active: '#7E9ABC',
    },
    status: {
      success: '#A3BE8C',
      successSubtle: '#F3F7F1',
      warning: '#EBCB8B',
      warningSubtle: '#FCF8F1',
      error: '#BF616A',
      errorSubtle: '#F7ECED',
      info: '#88C0D0',
      infoSubtle: '#F0F7F9',
    },
    border: {
      default: '#4C566A',
      subtle: '#434C5E',
      focus: '#5E81AC',
      hover: '#5D6678',
    },
    interactive: {
      default: '#383E49',
      hover: '#424853',
      active: '#4D525C',
      disabled: '#2E3440',
      focus: '#5E81AC',
    },
    input: {
      bg: '#434C5E',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#5E81AC',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(46, 52, 64, 0.75)',
      tooltip: '#1F2937',
      popover: '#424853',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#5E81AC', '#81A1C1', '#88C0D0', '#A3BE8C', '#EBCB8B'], positive: '#A3BE8C', negative: '#BF616A' },
};

export const tokyoNightTheme: VisualTheme = {
  id: 'tokyonight',
  name: 'Tokyo Night',
  description: 'Dark theme inspired by Tokyo city lights',
  category: 'dark',
  light: {
    bg: {
      primary: '#D5D6DB',
      secondary: '#CBCCD1',
      card: '#FFFFFF',
      sidebar: '#363B54',
      elevated: '#FFFFFF',
      hover: '#CECFD4',
      active: '#C8C9CD',
    },
    text: {
      primary: '#343B58',
      secondary: '#565A6E',
      muted: '#9699A3',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#7AA2F7',
      secondary: '#BB9AF7',
      tertiary: '#7DCFFF',
      hover: '#6B8ED9',
      active: '#6181C5',
    },
    status: {
      success: '#9ECE6A',
      successSubtle: '#F3F9ED',
      warning: '#E0AF68',
      warningSubtle: '#FBF5EC',
      error: '#F7768E',
      errorSubtle: '#FEEEF1',
      info: '#7DCFFF',
      infoSubtle: '#EFF9FF',
    },
    border: {
      default: '#C4C5CA',
      subtle: '#D5D6DB',
      focus: '#7AA2F7',
      hover: '#B0B1B5',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#7AA2F7',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#7AA2F7',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(52, 59, 88, 0.5)',
      tooltip: '#343B58',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#1A1B26',
      secondary: '#24283B',
      card: '#1F2335',
      sidebar: '#15161E',
      elevated: '#1F2335',
      hover: '#252630',
      active: '#30313B',
    },
    text: {
      primary: '#C0CAF5',
      secondary: '#A9B1D6',
      muted: '#565F89',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#7AA2F7',
      secondary: '#BB9AF7',
      tertiary: '#7DCFFF',
      hover: '#89ADF7',
      active: '#94B4F8',
    },
    status: {
      success: '#9ECE6A',
      successSubtle: '#F3F9ED',
      warning: '#E0AF68',
      warningSubtle: '#FBF5EC',
      error: '#F7768E',
      errorSubtle: '#FEEEF1',
      info: '#7DCFFF',
      infoSubtle: '#EFF9FF',
    },
    border: {
      default: '#3B4261',
      subtle: '#292E42',
      focus: '#7AA2F7',
      hover: '#4E5470',
    },
    interactive: {
      default: '#252630',
      hover: '#30313B',
      active: '#3C3D46',
      disabled: '#1A1B26',
      focus: '#7AA2F7',
    },
    input: {
      bg: '#1F2335',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#7AA2F7',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(26, 27, 38, 0.75)',
      tooltip: '#1F2937',
      popover: '#30313B',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#7AA2F7', '#BB9AF7', '#7DCFFF', '#9ECE6A', '#E0AF68'], positive: '#9ECE6A', negative: '#F7768E' },
};

export const monokaiTheme: VisualTheme = {
  id: 'monokai',
  name: 'Monokai',
  description: 'Classic dark theme with vibrant colors',
  category: 'dark',
  light: {
    bg: {
      primary: '#F8F8F2',
      secondary: '#E8E8E0',
      card: '#FFFFFF',
      sidebar: '#49483E',
      elevated: '#FFFFFF',
      hover: '#F0F0EA',
      active: '#E9E9E3',
    },
    text: {
      primary: '#272822',
      secondary: '#49483E',
      muted: '#75715E',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#A6E22E',
      secondary: '#F92672',
      tertiary: '#66D9EF',
      hover: '#92C628',
      active: '#84B424',
    },
    status: {
      success: '#A6E22E',
      successSubtle: '#F4FBE5',
      warning: '#E6DB74',
      warningSubtle: '#FCFAEE',
      error: '#F92672',
      errorSubtle: '#FEE4EE',
      info: '#66D9EF',
      infoSubtle: '#ECFAFD',
    },
    border: {
      default: '#DEDED8',
      subtle: '#E8E8E0',
      focus: '#A6E22E',
      hover: '#C7C7C2',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#A6E22E',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#A6E22E',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(39, 40, 34, 0.5)',
      tooltip: '#272822',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#272822',
      secondary: '#3E3D32',
      card: '#49483E',
      sidebar: '#1E1F1C',
      elevated: '#49483E',
      hover: '#31322D',
      active: '#3C3D38',
    },
    text: {
      primary: '#F8F8F2',
      secondary: '#CFCFC2',
      muted: '#75715E',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#A6E22E',
      secondary: '#F92672',
      tertiary: '#66D9EF',
      hover: '#B0E547',
      active: '#B7E757',
    },
    status: {
      success: '#A6E22E',
      successSubtle: '#F4FBE5',
      warning: '#E6DB74',
      warningSubtle: '#FCFAEE',
      error: '#F92672',
      errorSubtle: '#FEE4EE',
      info: '#66D9EF',
      infoSubtle: '#ECFAFD',
    },
    border: {
      default: '#49483E',
      subtle: '#3E3D32',
      focus: '#A6E22E',
      hover: '#5B5A51',
    },
    interactive: {
      default: '#31322D',
      hover: '#3C3D38',
      active: '#474843',
      disabled: '#272822',
      focus: '#A6E22E',
    },
    input: {
      bg: '#49483E',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#A6E22E',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(39, 40, 34, 0.75)',
      tooltip: '#1F2937',
      popover: '#3C3D38',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#A6E22E', '#F92672', '#66D9EF', '#E6DB74', '#FD971F'], positive: '#A6E22E', negative: '#F92672' },
};

export const solarizedDarkTheme: VisualTheme = {
  id: 'solarizeddark',
  name: 'Solarized Dark',
  description: 'Precision colors for machines and people',
  category: 'dark',
  light: {
    bg: {
      primary: '#FDF6E3',
      secondary: '#EEE8D5',
      card: '#FFFFFF',
      sidebar: '#073642',
      elevated: '#FFFFFF',
      hover: '#F5EEDC',
      active: '#EDE7D5',
    },
    text: {
      primary: '#073642',
      secondary: '#586E75',
      muted: '#93A1A1',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#268BD2',
      secondary: '#2AA198',
      tertiary: '#6C71C4',
      hover: '#217AB8',
      active: '#1E6FA8',
    },
    status: {
      success: '#859900',
      successSubtle: '#F0F2E0',
      warning: '#B58900',
      warningSubtle: '#F6F0E0',
      error: '#DC322F',
      errorSubtle: '#FAE6E6',
      info: '#268BD2',
      infoSubtle: '#E4F1F9',
    },
    border: {
      default: '#EEE8D5',
      subtle: '#FDF6E3',
      focus: '#268BD2',
      hover: '#D6D0BF',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#268BD2',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#268BD2',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(7, 54, 66, 0.5)',
      tooltip: '#073642',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#002B36',
      secondary: '#073642',
      card: '#073642',
      sidebar: '#001E26',
      elevated: '#073642',
      hover: '#0C3540',
      active: '#19404A',
    },
    text: {
      primary: '#FDF6E3',
      secondary: '#93A1A1',
      muted: '#657B83',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#268BD2',
      secondary: '#2AA198',
      tertiary: '#6C71C4',
      hover: '#4098D7',
      active: '#51A2DB',
    },
    status: {
      success: '#859900',
      successSubtle: '#F0F2E0',
      warning: '#B58900',
      warningSubtle: '#F6F0E0',
      error: '#DC322F',
      errorSubtle: '#FAE6E6',
      info: '#268BD2',
      infoSubtle: '#E4F1F9',
    },
    border: {
      default: '#586E75',
      subtle: '#073642',
      focus: '#268BD2',
      hover: '#687C82',
    },
    interactive: {
      default: '#0C3540',
      hover: '#19404A',
      active: '#264A54',
      disabled: '#002B36',
      focus: '#268BD2',
    },
    input: {
      bg: '#073642',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#268BD2',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(0, 43, 54, 0.75)',
      tooltip: '#1F2937',
      popover: '#19404A',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#268BD2', '#2AA198', '#6C71C4', '#859900', '#B58900'], positive: '#859900', negative: '#DC322F' },
};

export const gruvboxTheme: VisualTheme = {
  id: 'gruvbox',
  name: 'Gruvbox',
  description: 'Retro groove color scheme',
  category: 'dark',
  light: {
    bg: {
      primary: '#FBF1C7',
      secondary: '#EBDBB2',
      card: '#FFFFFF',
      sidebar: '#504945',
      elevated: '#FFFFFF',
      hover: '#F3E9C1',
      active: '#EBE2BB',
    },
    text: {
      primary: '#3C3836',
      secondary: '#504945',
      muted: '#7C6F64',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#D65D0E',
      secondary: '#458588',
      tertiary: '#98971A',
      hover: '#BC510C',
      active: '#AB4A0B',
    },
    status: {
      success: '#98971A',
      successSubtle: '#F2F2E3',
      warning: '#D79921',
      warningSubtle: '#FAF2E4',
      error: '#CC241D',
      errorSubtle: '#F8E4E3',
      info: '#458588',
      infoSubtle: '#E8F0F0',
    },
    border: {
      default: '#D5C4A1',
      subtle: '#EBDBB2',
      focus: '#D65D0E',
      hover: '#BFB090',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#D65D0E',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#D65D0E',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(60, 56, 54, 0.5)',
      tooltip: '#3C3836',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#282828',
      secondary: '#3C3836',
      card: '#504945',
      sidebar: '#1D2021',
      elevated: '#504945',
      hover: '#323232',
      active: '#3D3D3D',
    },
    text: {
      primary: '#EBDBB2',
      secondary: '#D5C4A1',
      muted: '#928374',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#FE8019',
      secondary: '#83A598',
      tertiary: '#B8BB26',
      hover: '#FE8F34',
      active: '#FE9947',
    },
    status: {
      success: '#B8BB26',
      successSubtle: '#F6F6E4',
      warning: '#FABD2F',
      warningSubtle: '#FEF7E6',
      error: '#FB4934',
      errorSubtle: '#FEE9E6',
      info: '#83A598',
      infoSubtle: '#F0F4F2',
    },
    border: {
      default: '#504945',
      subtle: '#3C3836',
      focus: '#FE8019',
      hover: '#615B57',
    },
    interactive: {
      default: '#323232',
      hover: '#3D3D3D',
      active: '#484848',
      disabled: '#282828',
      focus: '#FE8019',
    },
    input: {
      bg: '#504945',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#FE8019',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(40, 40, 40, 0.75)',
      tooltip: '#1F2937',
      popover: '#3D3D3D',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#FE8019', '#83A598', '#B8BB26', '#FABD2F', '#D3869B'], positive: '#B8BB26', negative: '#FB4934' },
};

export const catppuccinTheme: VisualTheme = {
  id: 'catppuccin',
  name: 'Catppuccin',
  description: 'Soothing pastel theme for the high-spirited',
  category: 'dark',
  light: {
    bg: {
      primary: '#EFF1F5',
      secondary: '#E6E9EF',
      card: '#FFFFFF',
      sidebar: '#5C5F77',
      elevated: '#FFFFFF',
      hover: '#E7E9ED',
      active: '#E0E2E6',
    },
    text: {
      primary: '#4C4F69',
      secondary: '#5C5F77',
      muted: '#8C8FA1',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#8839EF',
      secondary: '#E64553',
      tertiary: '#1E66F5',
      hover: '#7732D2',
      active: '#6C2DBF',
    },
    status: {
      success: '#40A02B',
      successSubtle: '#E8F3E5',
      warning: '#DF8E1D',
      warningSubtle: '#FBF1E3',
      error: '#D20F39',
      errorSubtle: '#F9E2E7',
      info: '#1E66F5',
      infoSubtle: '#E4ECFD',
    },
    border: {
      default: '#CCD0DA',
      subtle: '#E6E9EF',
      focus: '#8839EF',
      hover: '#B7BBC4',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#8839EF',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#8839EF',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(76, 79, 105, 0.5)',
      tooltip: '#4C4F69',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#1E1E2E',
      secondary: '#313244',
      card: '#45475A',
      sidebar: '#181825',
      elevated: '#45475A',
      hover: '#292938',
      active: '#343442',
    },
    text: {
      primary: '#CDD6F4',
      secondary: '#BAC2DE',
      muted: '#6C7086',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#CBA6F7',
      secondary: '#F38BA8',
      tertiary: '#89B4FA',
      hover: '#D1B0F7',
      active: '#D5B7F8',
    },
    status: {
      success: '#A6E3A1',
      successSubtle: '#F4FBF3',
      warning: '#FAB387',
      warningSubtle: '#FEF5F0',
      error: '#F38BA8',
      errorSubtle: '#FDF1F4',
      info: '#89B4FA',
      infoSubtle: '#F0F6FE',
    },
    border: {
      default: '#45475A',
      subtle: '#313244',
      focus: '#CBA6F7',
      hover: '#57596A',
    },
    interactive: {
      default: '#292938',
      hover: '#343442',
      active: '#3F3F4D',
      disabled: '#1E1E2E',
      focus: '#CBA6F7',
    },
    input: {
      bg: '#45475A',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#CBA6F7',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(30, 30, 46, 0.75)',
      tooltip: '#1F2937',
      popover: '#343442',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#CBA6F7', '#F38BA8', '#89B4FA', '#A6E3A1', '#FAB387'], positive: '#A6E3A1', negative: '#F38BA8' },
};

export const oneDarkTheme: VisualTheme = {
  id: 'onedark',
  name: 'One Dark',
  description: 'Atom One Dark inspired theme',
  category: 'dark',
  light: {
    bg: {
      primary: '#FAFAFA',
      secondary: '#F0F0F0',
      card: '#FFFFFF',
      sidebar: '#383C4A',
      elevated: '#FFFFFF',
      hover: '#F2F2F2',
      active: '#EBEBEB',
    },
    text: {
      primary: '#383A42',
      secondary: '#4F525D',
      muted: '#9D9D9F',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#4078F2',
      secondary: '#A626A4',
      tertiary: '#0184BC',
      hover: '#3869D4',
      active: '#3360C1',
    },
    status: {
      success: '#50A14F',
      successSubtle: '#EAF3E9',
      warning: '#C18401',
      warningSubtle: '#F7F0E0',
      error: '#E45649',
      errorSubtle: '#FBEAE9',
      info: '#0184BC',
      infoSubtle: '#E0F0F6',
    },
    border: {
      default: '#E1E1E1',
      subtle: '#F0F0F0',
      focus: '#4078F2',
      hover: '#CACACA',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#4078F2',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#4078F2',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(56, 58, 66, 0.5)',
      tooltip: '#383A42',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#282C34',
      secondary: '#21252B',
      card: '#2C313C',
      sidebar: '#1E2127',
      elevated: '#2C313C',
      hover: '#32363E',
      active: '#3D4148',
    },
    text: {
      primary: '#ABB2BF',
      secondary: '#9DA5B4',
      muted: '#5C6370',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#61AFEF',
      secondary: '#C678DD',
      tertiary: '#56B6C2',
      hover: '#73B8F0',
      active: '#80BFF2',
    },
    status: {
      success: '#98C379',
      successSubtle: '#F2F7EE',
      warning: '#E5C07B',
      warningSubtle: '#FBF7EF',
      error: '#E06C75',
      errorSubtle: '#FBEDEE',
      info: '#56B6C2',
      infoSubtle: '#EAF6F7',
    },
    border: {
      default: '#3E4451',
      subtle: '#2C313C',
      focus: '#61AFEF',
      hover: '#515662',
    },
    interactive: {
      default: '#32363E',
      hover: '#3D4148',
      active: '#484B52',
      disabled: '#282C34',
      focus: '#61AFEF',
    },
    input: {
      bg: '#2C313C',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#61AFEF',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(40, 44, 52, 0.75)',
      tooltip: '#1F2937',
      popover: '#3D4148',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#61AFEF', '#C678DD', '#56B6C2', '#98C379', '#E5C07B'], positive: '#98C379', negative: '#E06C75' },
};

export const synthwaveTheme: VisualTheme = {
  id: 'synthwave',
  name: 'Synthwave',
  description: 'Retro-futuristic neon vibes',
  category: 'dark',
  light: {
    bg: {
      primary: '#F8F0FF',
      secondary: '#EEE0FF',
      card: '#FFFFFF',
      sidebar: '#2A2041',
      elevated: '#FFFFFF',
      hover: '#F0E8F7',
      active: '#E9E1EF',
    },
    text: {
      primary: '#2A2041',
      secondary: '#4A3A61',
      muted: '#7A6A91',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#FF7EDB',
      secondary: '#72F1B8',
      tertiary: '#FDE987',
      hover: '#E06EC0',
      active: '#CC64AF',
    },
    status: {
      success: '#72F1B8',
      successSubtle: '#EEFDF6',
      warning: '#FDE987',
      warningSubtle: '#FEFCF0',
      error: '#FE4450',
      errorSubtle: '#FEE8EA',
      info: '#36F9F6',
      infoSubtle: '#E6FEFD',
    },
    border: {
      default: '#E0D0F0',
      subtle: '#EEE0FF',
      focus: '#FF7EDB',
      hover: '#C9BBD8',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#FF7EDB',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#FF7EDB',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(42, 32, 65, 0.5)',
      tooltip: '#2A2041',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#2A2041',
      secondary: '#1A1030',
      card: '#34294F',
      sidebar: '#120B1E',
      elevated: '#34294F',
      hover: '#342B4A',
      active: '#3F3654',
    },
    text: {
      primary: '#F0E6FF',
      secondary: '#C6B6E6',
      muted: '#7A6A91',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#FF7EDB',
      secondary: '#72F1B8',
      tertiary: '#FDE987',
      hover: '#FF8DDF',
      active: '#FF97E2',
    },
    status: {
      success: '#72F1B8',
      successSubtle: '#EEFDF6',
      warning: '#FDE987',
      warningSubtle: '#FEFCF0',
      error: '#FE4450',
      errorSubtle: '#FEE8EA',
      info: '#36F9F6',
      infoSubtle: '#E6FEFD',
    },
    border: {
      default: '#4A3A61',
      subtle: '#34294F',
      focus: '#FF7EDB',
      hover: '#5C4D70',
    },
    interactive: {
      default: '#342B4A',
      hover: '#3F3654',
      active: '#49415D',
      disabled: '#2A2041',
      focus: '#FF7EDB',
    },
    input: {
      bg: '#34294F',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#FF7EDB',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(42, 32, 65, 0.75)',
      tooltip: '#1F2937',
      popover: '#3F3654',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#FF7EDB', '#72F1B8', '#36F9F6', '#FDE987', '#FE4450'], positive: '#72F1B8', negative: '#FE4450' },
};

export const forestTheme: VisualTheme = {
  id: 'forest',
  name: 'Forest',
  description: 'Deep green nature-inspired palette',
  category: 'dark',
  light: {
    bg: {
      primary: '#F5F9F5',
      secondary: '#E8F0E8',
      card: '#FFFFFF',
      sidebar: '#2D4A3E',
      elevated: '#FFFFFF',
      hover: '#EDF1ED',
      active: '#E6EAE6',
    },
    text: {
      primary: '#1A2E24',
      secondary: '#3A5A4A',
      muted: '#6A8A7A',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#2E7D32',
      secondary: '#4CAF50',
      tertiary: '#81C784',
      hover: '#286E2C',
      active: '#246428',
    },
    status: {
      success: '#2E7D32',
      successSubtle: '#E5EFE6',
      warning: '#F9A825',
      warningSubtle: '#FEF4E4',
      error: '#C62828',
      errorSubtle: '#F8E5E5',
      info: '#0288D1',
      infoSubtle: '#E0F0F9',
    },
    border: {
      default: '#D4E4D4',
      subtle: '#E8F0E8',
      focus: '#2E7D32',
      hover: '#BECDBE',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#2E7D32',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#2E7D32',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(26, 46, 36, 0.5)',
      tooltip: '#1A2E24',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#1A2E24',
      secondary: '#243B30',
      card: '#2D4A3E',
      sidebar: '#0F1C14',
      elevated: '#2D4A3E',
      hover: '#25382E',
      active: '#304239',
    },
    text: {
      primary: '#E8F5E9',
      secondary: '#A5D6A7',
      muted: '#6A8A7A',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#4CAF50',
      secondary: '#66BB6A',
      tertiary: '#81C784',
      hover: '#61B865',
      active: '#6FBF73',
    },
    status: {
      success: '#4CAF50',
      successSubtle: '#E9F5EA',
      warning: '#FFC107',
      warningSubtle: '#FFF7E1',
      error: '#EF5350',
      errorSubtle: '#FDEAEA',
      info: '#29B6F6',
      infoSubtle: '#E5F6FD',
    },
    border: {
      default: '#3A5A4A',
      subtle: '#2D4A3E',
      focus: '#4CAF50',
      hover: '#4D6A5C',
    },
    interactive: {
      default: '#25382E',
      hover: '#304239',
      active: '#3C4D44',
      disabled: '#1A2E24',
      focus: '#4CAF50',
    },
    input: {
      bg: '#2D4A3E',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#4CAF50',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(26, 46, 36, 0.75)',
      tooltip: '#1F2937',
      popover: '#304239',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#4CAF50', '#66BB6A', '#81C784', '#0288D1', '#F9A825'], positive: '#4CAF50', negative: '#EF5350' },
};

export const oceanTheme: VisualTheme = {
  id: 'ocean',
  name: 'Ocean',
  description: 'Deep blue oceanic color palette',
  category: 'dark',
  light: {
    bg: {
      primary: '#F0F7FA',
      secondary: '#E0EFF5',
      card: '#FFFFFF',
      sidebar: '#1A3A5C',
      elevated: '#FFFFFF',
      hover: '#E8EFF2',
      active: '#E1E8EB',
    },
    text: {
      primary: '#0A2540',
      secondary: '#2A5A80',
      muted: '#5A8AAA',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#0288D1',
      secondary: '#03A9F4',
      tertiary: '#4FC3F7',
      hover: '#0177B7',
      active: '#016CA7',
    },
    status: {
      success: '#00897B',
      successSubtle: '#E0F0EF',
      warning: '#FFA726',
      warningSubtle: '#FFF4E4',
      error: '#E53935',
      errorSubtle: '#FBE7E6',
      info: '#0288D1',
      infoSubtle: '#E0F0F9',
    },
    border: {
      default: '#C0D5E5',
      subtle: '#E0EFF5',
      focus: '#0288D1',
      hover: '#ACBFCE',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#0288D1',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#0288D1',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(10, 37, 64, 0.5)',
      tooltip: '#0A2540',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#0A2540',
      secondary: '#1A3A5C',
      card: '#2A4A6C',
      sidebar: '#051A2C',
      elevated: '#2A4A6C',
      hover: '#162F49',
      active: '#223A53',
    },
    text: {
      primary: '#E3F2FD',
      secondary: '#90CAF9',
      muted: '#5A8AAA',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#29B6F6',
      secondary: '#4FC3F7',
      tertiary: '#81D4FA',
      hover: '#42BEF7',
      active: '#53C4F7',
    },
    status: {
      success: '#26A69A',
      successSubtle: '#E4F4F2',
      warning: '#FFCA28',
      warningSubtle: '#FFF8E5',
      error: '#EF5350',
      errorSubtle: '#FDEAEA',
      info: '#29B6F6',
      infoSubtle: '#E5F6FD',
    },
    border: {
      default: '#3A5A7C',
      subtle: '#2A4A6C',
      focus: '#29B6F6',
      hover: '#4D6A89',
    },
    interactive: {
      default: '#162F49',
      hover: '#223A53',
      active: '#2E455C',
      disabled: '#0A2540',
      focus: '#29B6F6',
    },
    input: {
      bg: '#2A4A6C',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#29B6F6',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(10, 37, 64, 0.75)',
      tooltip: '#1F2937',
      popover: '#223A53',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#29B6F6', '#4FC3F7', '#81D4FA', '#26A69A', '#FFCA28'], positive: '#26A69A', negative: '#EF5350' },
};

export const retroTheme: VisualTheme = {
  id: 'retro',
  name: 'Retro',
  description: 'Vintage computing aesthetic',
  category: 'dark',
  light: {
    bg: {
      primary: '#FFF8E7',
      secondary: '#FFF0D0',
      card: '#FFFFFF',
      sidebar: '#5D4E37',
      elevated: '#FFFFFF',
      hover: '#F7F0E0',
      active: '#EFE9D9',
    },
    text: {
      primary: '#3D2E17',
      secondary: '#5D4E37',
      muted: '#8D7E67',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#C73E1D',
      secondary: '#2E86AB',
      tertiary: '#A23B72',
      hover: '#AF3619',
      active: '#9F3117',
    },
    status: {
      success: '#5D8233',
      successSubtle: '#EBF0E6',
      warning: '#D4A017',
      warningSubtle: '#F9F3E3',
      error: '#C73E1D',
      errorSubtle: '#F8E7E3',
      info: '#2E86AB',
      infoSubtle: '#E5F0F4',
    },
    border: {
      default: '#E8D8B8',
      subtle: '#FFF0D0',
      focus: '#C73E1D',
      hover: '#D0C2A5',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#C73E1D',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#C73E1D',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(61, 46, 23, 0.5)',
      tooltip: '#3D2E17',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#2D2013',
      secondary: '#3D3023',
      card: '#4D4033',
      sidebar: '#1D1008',
      elevated: '#4D4033',
      hover: '#372B1E',
      active: '#42362A',
    },
    text: {
      primary: '#FFF8E7',
      secondary: '#E8D8B8',
      muted: '#8D7E67',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#FF6B35',
      secondary: '#5BC0EB',
      tertiary: '#D64292',
      hover: '#FF7C4D',
      active: '#FF885D',
    },
    status: {
      success: '#9BC53D',
      successSubtle: '#F3F8E7',
      warning: '#FDE74C',
      warningSubtle: '#FEFCE9',
      error: '#FF6B35',
      errorSubtle: '#FFEDE6',
      info: '#5BC0EB',
      infoSubtle: '#EBF7FC',
    },
    border: {
      default: '#5D4E37',
      subtle: '#4D4033',
      focus: '#FF6B35',
      hover: '#6D5F4B',
    },
    interactive: {
      default: '#372B1E',
      hover: '#42362A',
      active: '#4C4136',
      disabled: '#2D2013',
      focus: '#FF6B35',
    },
    input: {
      bg: '#4D4033',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#FF6B35',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(45, 32, 19, 0.75)',
      tooltip: '#1F2937',
      popover: '#42362A',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#FF6B35', '#5BC0EB', '#D64292', '#9BC53D', '#FDE74C'], positive: '#9BC53D', negative: '#FF6B35' },
};

// ==================== LIGHT THEMES ====================

export const creamTheme: VisualTheme = {
  id: 'cream',
  name: 'Cream',
  description: 'Soft, warm off-white palette',
  category: 'light',
  light: {
    bg: {
      primary: '#FFFDF5',
      secondary: '#FFF8E8',
      card: '#FFFFFF',
      sidebar: '#8B7355',
      elevated: '#FFFFFF',
      hover: '#F7F5ED',
      active: '#EFEDE6',
    },
    text: {
      primary: '#4A4035',
      secondary: '#6B5B45',
      muted: '#9B8B75',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#B8860B',
      secondary: '#CD950C',
      tertiary: '#DAA520',
      hover: '#A17509',
      active: '#936B08',
    },
    status: {
      success: '#6B8E23',
      successSubtle: '#EDF1E4',
      warning: '#DAA520',
      warningSubtle: '#FAF4E4',
      error: '#CD5C5C',
      errorSubtle: '#F9EBEB',
      info: '#4682B4',
      infoSubtle: '#E8F0F6',
    },
    border: {
      default: '#E8DCC8',
      subtle: '#F5EFE0',
      focus: '#B8860B',
      hover: '#D0C6B4',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#B8860B',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#B8860B',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(74, 64, 53, 0.5)',
      tooltip: '#4A4035',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#2A2520',
      secondary: '#3A3530',
      card: '#4A4540',
      sidebar: '#1A1510',
      elevated: '#4A4540',
      hover: '#342F2B',
      active: '#3F3A36',
    },
    text: {
      primary: '#FFF8E8',
      secondary: '#E8DCC8',
      muted: '#9B8B75',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#DAA520',
      secondary: '#F0C040',
      tertiary: '#FFD700',
      hover: '#DEAF3A',
      active: '#E1B74C',
    },
    status: {
      success: '#9ACD32',
      successSubtle: '#F2F9E6',
      warning: '#FFD700',
      warningSubtle: '#FFFAE0',
      error: '#FA8072',
      errorSubtle: '#FEEFEE',
      info: '#87CEEB',
      infoSubtle: '#F0F9FC',
    },
    border: {
      default: '#5A5550',
      subtle: '#4A4540',
      focus: '#DAA520',
      hover: '#6A6661',
    },
    interactive: {
      default: '#342F2B',
      hover: '#3F3A36',
      active: '#494541',
      disabled: '#2A2520',
      focus: '#DAA520',
    },
    input: {
      bg: '#4A4540',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#DAA520',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(42, 37, 32, 0.75)',
      tooltip: '#1F2937',
      popover: '#3F3A36',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#DAA520', '#6B8E23', '#4682B4', '#CD5C5C', '#B8860B'], positive: '#6B8E23', negative: '#CD5C5C' },
};

export const solarizedLightTheme: VisualTheme = {
  id: 'solarizedlight',
  name: 'Solarized Light',
  description: 'Precision colors with light background',
  category: 'light',
  light: {
    bg: {
      primary: '#FDF6E3',
      secondary: '#EEE8D5',
      card: '#FFFFFF',
      sidebar: '#002B36',
      elevated: '#FFFFFF',
      hover: '#F5EEDC',
      active: '#EDE7D5',
    },
    text: {
      primary: '#657B83',
      secondary: '#839496',
      muted: '#93A1A1',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#268BD2',
      secondary: '#2AA198',
      tertiary: '#6C71C4',
      hover: '#217AB8',
      active: '#1E6FA8',
    },
    status: {
      success: '#859900',
      successSubtle: '#F0F2E0',
      warning: '#B58900',
      warningSubtle: '#F6F0E0',
      error: '#DC322F',
      errorSubtle: '#FAE6E6',
      info: '#268BD2',
      infoSubtle: '#E4F1F9',
    },
    border: {
      default: '#EEE8D5',
      subtle: '#FDF6E3',
      focus: '#268BD2',
      hover: '#D6D0BF',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#268BD2',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#268BD2',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(101, 123, 131, 0.5)',
      tooltip: '#657B83',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#002B36',
      secondary: '#073642',
      card: '#073642',
      sidebar: '#001E26',
      elevated: '#073642',
      hover: '#0C3540',
      active: '#19404A',
    },
    text: {
      primary: '#FDF6E3',
      secondary: '#93A1A1',
      muted: '#657B83',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#268BD2',
      secondary: '#2AA198',
      tertiary: '#6C71C4',
      hover: '#4098D7',
      active: '#51A2DB',
    },
    status: {
      success: '#859900',
      successSubtle: '#F0F2E0',
      warning: '#B58900',
      warningSubtle: '#F6F0E0',
      error: '#DC322F',
      errorSubtle: '#FAE6E6',
      info: '#268BD2',
      infoSubtle: '#E4F1F9',
    },
    border: {
      default: '#586E75',
      subtle: '#073642',
      focus: '#268BD2',
      hover: '#687C82',
    },
    interactive: {
      default: '#0C3540',
      hover: '#19404A',
      active: '#264A54',
      disabled: '#002B36',
      focus: '#268BD2',
    },
    input: {
      bg: '#073642',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#268BD2',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(0, 43, 54, 0.75)',
      tooltip: '#1F2937',
      popover: '#19404A',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#268BD2', '#2AA198', '#6C71C4', '#859900', '#B58900'], positive: '#859900', negative: '#DC322F' },
};

export const githubTheme: VisualTheme = {
  id: 'github',
  name: 'GitHub',
  description: 'Clean, professional developer theme',
  category: 'light',
  light: {
    bg: {
      primary: '#FFFFFF',
      secondary: '#F6F8FA',
      card: '#FFFFFF',
      sidebar: '#24292F',
      elevated: '#FFFFFF',
      hover: '#F7F7F7',
      active: '#EFEFEF',
    },
    text: {
      primary: '#24292F',
      secondary: '#57606A',
      muted: '#8B949E',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#0969DA',
      secondary: '#1F883D',
      tertiary: '#8250DF',
      hover: '#075CBF',
      active: '#0754AE',
    },
    status: {
      success: '#1F883D',
      successSubtle: '#E4F0E7',
      warning: '#D29922',
      warningSubtle: '#F9F2E4',
      error: '#CF222E',
      errorSubtle: '#F9E4E5',
      info: '#0969DA',
      infoSubtle: '#E1EDFA',
    },
    border: {
      default: '#D0D7DE',
      subtle: '#F6F8FA',
      focus: '#0969DA',
      hover: '#BBC1C7',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#0969DA',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#0969DA',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(36, 41, 47, 0.5)',
      tooltip: '#24292F',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#0D1117',
      secondary: '#161B22',
      card: '#21262D',
      sidebar: '#010409',
      elevated: '#21262D',
      hover: '#191C22',
      active: '#25282E',
    },
    text: {
      primary: '#E6EDF3',
      secondary: '#8B949E',
      muted: '#6E7681',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#2F81F7',
      secondary: '#3FB950',
      tertiary: '#A371F7',
      hover: '#4790F7',
      active: '#589AF8',
    },
    status: {
      success: '#3FB950',
      successSubtle: '#E7F6EA',
      warning: '#D29922',
      warningSubtle: '#F9F2E4',
      error: '#F85149',
      errorSubtle: '#FEEAE9',
      info: '#2F81F7',
      infoSubtle: '#E6EFFE',
    },
    border: {
      default: '#30363D',
      subtle: '#21262D',
      focus: '#2F81F7',
      hover: '#444A50',
    },
    interactive: {
      default: '#191C22',
      hover: '#25282E',
      active: '#313439',
      disabled: '#0D1117',
      focus: '#2F81F7',
    },
    input: {
      bg: '#21262D',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#2F81F7',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(13, 17, 23, 0.75)',
      tooltip: '#1F2937',
      popover: '#25282E',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#0969DA', '#1F883D', '#8250DF', '#D29922', '#CF222E'], positive: '#1F883D', negative: '#CF222E' },
};

export const paperTheme: VisualTheme = {
  id: 'paper',
  name: 'Paper',
  description: 'Clean minimalist white theme',
  category: 'light',
  light: {
    bg: {
      primary: '#FAFAFA',
      secondary: '#F5F5F5',
      card: '#FFFFFF',
      sidebar: '#424242',
      elevated: '#FFFFFF',
      hover: '#F2F2F2',
      active: '#EBEBEB',
    },
    text: {
      primary: '#212121',
      secondary: '#616161',
      muted: '#9E9E9E',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#1976D2',
      secondary: '#1E88E5',
      tertiary: '#42A5F5',
      hover: '#1667B8',
      active: '#145EA8',
    },
    status: {
      success: '#388E3C',
      successSubtle: '#E7F1E7',
      warning: '#F57C00',
      warningSubtle: '#FDEFE0',
      error: '#D32F2F',
      errorSubtle: '#F9E6E6',
      info: '#1976D2',
      infoSubtle: '#E3EEF9',
    },
    border: {
      default: '#E0E0E0',
      subtle: '#F5F5F5',
      focus: '#1976D2',
      hover: '#C9C9C9',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#1976D2',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#1976D2',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(33, 33, 33, 0.5)',
      tooltip: '#212121',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#121212',
      secondary: '#1E1E1E',
      card: '#2D2D2D',
      sidebar: '#0A0A0A',
      elevated: '#2D2D2D',
      hover: '#1D1D1D',
      active: '#292929',
    },
    text: {
      primary: '#FAFAFA',
      secondary: '#BDBDBD',
      muted: '#757575',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#64B5F6',
      secondary: '#42A5F5',
      tertiary: '#90CAF9',
      hover: '#76BDF7',
      active: '#83C3F7',
    },
    status: {
      success: '#81C784',
      successSubtle: '#EFF8F0',
      warning: '#FFB74D',
      warningSubtle: '#FFF6E9',
      error: '#E57373',
      errorSubtle: '#FBEEEE',
      info: '#64B5F6',
      infoSubtle: '#ECF6FD',
    },
    border: {
      default: '#424242',
      subtle: '#2D2D2D',
      focus: '#64B5F6',
      hover: '#545454',
    },
    interactive: {
      default: '#1D1D1D',
      hover: '#292929',
      active: '#353535',
      disabled: '#121212',
      focus: '#64B5F6',
    },
    input: {
      bg: '#2D2D2D',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#64B5F6',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(18, 18, 18, 0.75)',
      tooltip: '#1F2937',
      popover: '#292929',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#1976D2', '#388E3C', '#F57C00', '#7B1FA2', '#C2185B'], positive: '#388E3C', negative: '#D32F2F' },
};

export const roseTheme: VisualTheme = {
  id: 'rose',
  name: 'Rose',
  description: 'Elegant pink and rose palette',
  category: 'light',
  light: {
    bg: {
      primary: '#FFF5F7',
      secondary: '#FFE4E9',
      card: '#FFFFFF',
      sidebar: '#9D174D',
      elevated: '#FFFFFF',
      hover: '#F7EDEF',
      active: '#EFE6E8',
    },
    text: {
      primary: '#4A1A2C',
      secondary: '#7A3A5C',
      muted: '#AA6A8C',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#E11D48',
      secondary: '#F43F5E',
      tertiary: '#FB7185',
      hover: '#C6193F',
      active: '#B41739',
    },
    status: {
      success: '#059669',
      successSubtle: '#E1F2ED',
      warning: '#D97706',
      warningSubtle: '#FAEEE1',
      error: '#DC2626',
      errorSubtle: '#FAE4E4',
      info: '#2563EB',
      infoSubtle: '#E4ECFC',
    },
    border: {
      default: '#FECDD3',
      subtle: '#FFE4E9',
      focus: '#E11D48',
      hover: '#E4B8BD',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#E11D48',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#E11D48',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(74, 26, 44, 0.5)',
      tooltip: '#4A1A2C',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#1C0A10',
      secondary: '#2C1A20',
      card: '#3C2A30',
      sidebar: '#0C0008',
      elevated: '#3C2A30',
      hover: '#27161B',
      active: '#322227',
    },
    text: {
      primary: '#FFF5F7',
      secondary: '#FECDD3',
      muted: '#AA6A8C',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#FB7185',
      secondary: '#FDA4AF',
      tertiary: '#FECDD3',
      hover: '#FB8293',
      active: '#FB8D9D',
    },
    status: {
      success: '#34D399',
      successSubtle: '#E6F9F2',
      warning: '#FBBF24',
      warningSubtle: '#FEF7E4',
      error: '#F87171',
      errorSubtle: '#FEEDED',
      info: '#60A5FA',
      infoSubtle: '#EBF4FE',
    },
    border: {
      default: '#5C3A40',
      subtle: '#3C2A30',
      focus: '#FB7185',
      hover: '#6C4D53',
    },
    interactive: {
      default: '#27161B',
      hover: '#322227',
      active: '#3E2E33',
      disabled: '#1C0A10',
      focus: '#FB7185',
    },
    input: {
      bg: '#3C2A30',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#FB7185',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(28, 10, 16, 0.75)',
      tooltip: '#1F2937',
      popover: '#322227',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#E11D48', '#F43F5E', '#FB7185', '#059669', '#D97706'], positive: '#059669', negative: '#DC2626' },
};

export const mintTheme: VisualTheme = {
  id: 'mint',
  name: 'Mint',
  description: 'Fresh, cool mint green palette',
  category: 'light',
  light: {
    bg: {
      primary: '#F0FDF4',
      secondary: '#DCFCE7',
      card: '#FFFFFF',
      sidebar: '#166534',
      elevated: '#FFFFFF',
      hover: '#E8F5EC',
      active: '#E1EDE5',
    },
    text: {
      primary: '#14532D',
      secondary: '#166534',
      muted: '#4ADE80',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#10B981',
      secondary: '#34D399',
      tertiary: '#6EE7B7',
      hover: '#0EA271',
      active: '#0C9467',
    },
    status: {
      success: '#10B981',
      successSubtle: '#E2F6EF',
      warning: '#F59E0B',
      warningSubtle: '#FDF3E1',
      error: '#EF4444',
      errorSubtle: '#FDE8E8',
      info: '#0EA5E9',
      infoSubtle: '#E2F4FC',
    },
    border: {
      default: '#BBF7D0',
      subtle: '#DCFCE7',
      focus: '#10B981',
      hover: '#A8DEBB',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#10B981',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#10B981',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(20, 83, 45, 0.5)',
      tooltip: '#14532D',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#052E16',
      secondary: '#14532D',
      card: '#166534',
      sidebar: '#022C10',
      elevated: '#166534',
      hover: '#113821',
      active: '#1E422D',
    },
    text: {
      primary: '#F0FDF4',
      secondary: '#BBF7D0',
      muted: '#4ADE80',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#34D399',
      secondary: '#6EE7B7',
      tertiary: '#A7F3D0',
      hover: '#4CD8A5',
      active: '#5CDBAD',
    },
    status: {
      success: '#34D399',
      successSubtle: '#E6F9F2',
      warning: '#FBBF24',
      warningSubtle: '#FEF7E4',
      error: '#F87171',
      errorSubtle: '#FEEDED',
      info: '#38BDF8',
      infoSubtle: '#E7F7FE',
    },
    border: {
      default: '#22C55E',
      subtle: '#166534',
      focus: '#34D399',
      hover: '#38CA6E',
    },
    interactive: {
      default: '#113821',
      hover: '#1E422D',
      active: '#2A4D38',
      disabled: '#052E16',
      focus: '#34D399',
    },
    input: {
      bg: '#166534',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#34D399',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(5, 46, 22, 0.75)',
      tooltip: '#1F2937',
      popover: '#1E422D',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#10B981', '#34D399', '#6EE7B7', '#0EA5E9', '#F59E0B'], positive: '#10B981', negative: '#EF4444' },
};

export const lavenderTheme: VisualTheme = {
  id: 'lavender',
  name: 'Lavender',
  description: 'Soft purple calming palette',
  category: 'light',
  light: {
    bg: {
      primary: '#FAF5FF',
      secondary: '#F3E8FF',
      card: '#FFFFFF',
      sidebar: '#6B21A8',
      elevated: '#FFFFFF',
      hover: '#F2EDF7',
      active: '#EBE6EF',
    },
    text: {
      primary: '#3B0764',
      secondary: '#6B21A8',
      muted: '#A855F7',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#9333EA',
      secondary: '#A855F7',
      tertiary: '#C084FC',
      hover: '#812CCD',
      active: '#7528BB',
    },
    status: {
      success: '#22C55E',
      successSubtle: '#E4F8EB',
      warning: '#EAB308',
      warningSubtle: '#FCF5E1',
      error: '#EF4444',
      errorSubtle: '#FDE8E8',
      info: '#3B82F6',
      infoSubtle: '#E7F0FD',
    },
    border: {
      default: '#E9D5FF',
      subtle: '#F3E8FF',
      focus: '#9333EA',
      hover: '#D1BFE5',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#9333EA',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#9333EA',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(59, 7, 100, 0.5)',
      tooltip: '#3B0764',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#1E0A2E',
      secondary: '#2E1A3E',
      card: '#3E2A4E',
      sidebar: '#0E0018',
      elevated: '#3E2A4E',
      hover: '#291638',
      active: '#342242',
    },
    text: {
      primary: '#FAF5FF',
      secondary: '#E9D5FF',
      muted: '#A855F7',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#A855F7',
      secondary: '#C084FC',
      tertiary: '#D8B4FE',
      hover: '#B269F7',
      active: '#B977F8',
    },
    status: {
      success: '#4ADE80',
      successSubtle: '#E9FBEF',
      warning: '#FACC15',
      warningSubtle: '#FEF8E2',
      error: '#F87171',
      errorSubtle: '#FEEDED',
      info: '#60A5FA',
      infoSubtle: '#EBF4FE',
    },
    border: {
      default: '#6B21A8',
      subtle: '#3E2A4E',
      focus: '#A855F7',
      hover: '#7937B0',
    },
    interactive: {
      default: '#291638',
      hover: '#342242',
      active: '#3F2E4D',
      disabled: '#1E0A2E',
      focus: '#A855F7',
    },
    input: {
      bg: '#3E2A4E',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#A855F7',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(30, 10, 46, 0.75)',
      tooltip: '#1F2937',
      popover: '#342242',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#9333EA', '#A855F7', '#C084FC', '#22C55E', '#EAB308'], positive: '#22C55E', negative: '#EF4444' },
};

export const skyTheme: VisualTheme = {
  id: 'sky',
  name: 'Sky',
  description: 'Light, airy sky blue palette',
  category: 'light',
  light: {
    bg: {
      primary: '#F0F9FF',
      secondary: '#E0F2FE',
      card: '#FFFFFF',
      sidebar: '#0369A1',
      elevated: '#FFFFFF',
      hover: '#E8F1F7',
      active: '#E1EAEF',
    },
    text: {
      primary: '#0C4A6E',
      secondary: '#0369A1',
      muted: '#38BDF8',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#0EA5E9',
      secondary: '#38BDF8',
      tertiary: '#7DD3FC',
      hover: '#0C91CD',
      active: '#0B84BA',
    },
    status: {
      success: '#22C55E',
      successSubtle: '#E4F8EB',
      warning: '#F59E0B',
      warningSubtle: '#FDF3E1',
      error: '#EF4444',
      errorSubtle: '#FDE8E8',
      info: '#0EA5E9',
      infoSubtle: '#E2F4FC',
    },
    border: {
      default: '#BAE6FD',
      subtle: '#E0F2FE',
      focus: '#0EA5E9',
      hover: '#A7CFE3',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#0EA5E9',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#0EA5E9',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(12, 74, 110, 0.5)',
      tooltip: '#0C4A6E',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#0A1929',
      secondary: '#0C4A6E',
      card: '#0369A1',
      sidebar: '#051320',
      elevated: '#0369A1',
      hover: '#162433',
      active: '#22303E',
    },
    text: {
      primary: '#F0F9FF',
      secondary: '#BAE6FD',
      muted: '#38BDF8',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#38BDF8',
      secondary: '#7DD3FC',
      tertiary: '#BAE6FD',
      hover: '#4FC4F8',
      active: '#5FCAF9',
    },
    status: {
      success: '#4ADE80',
      successSubtle: '#E9FBEF',
      warning: '#FBBF24',
      warningSubtle: '#FEF7E4',
      error: '#F87171',
      errorSubtle: '#FEEDED',
      info: '#38BDF8',
      infoSubtle: '#E7F7FE',
    },
    border: {
      default: '#0EA5E9',
      subtle: '#0369A1',
      focus: '#38BDF8',
      hover: '#26AEEB',
    },
    interactive: {
      default: '#162433',
      hover: '#22303E',
      active: '#2E3B49',
      disabled: '#0A1929',
      focus: '#38BDF8',
    },
    input: {
      bg: '#0369A1',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#38BDF8',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(10, 25, 41, 0.75)',
      tooltip: '#1F2937',
      popover: '#22303E',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#0EA5E9', '#38BDF8', '#7DD3FC', '#22C55E', '#F59E0B'], positive: '#22C55E', negative: '#EF4444' },
};

export const peachTheme: VisualTheme = {
  id: 'peach',
  name: 'Peach',
  description: 'Warm, soft peach and coral palette',
  category: 'light',
  light: {
    bg: {
      primary: '#FFF7ED',
      secondary: '#FFEDD5',
      card: '#FFFFFF',
      sidebar: '#C2410C',
      elevated: '#FFFFFF',
      hover: '#F7EFE5',
      active: '#EFE8DE',
    },
    text: {
      primary: '#431407',
      secondary: '#9A3412',
      muted: '#FB923C',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#F97316',
      secondary: '#FB923C',
      tertiary: '#FDBA74',
      hover: '#DB6513',
      active: '#C75C11',
    },
    status: {
      success: '#22C55E',
      successSubtle: '#E4F8EB',
      warning: '#EAB308',
      warningSubtle: '#FCF5E1',
      error: '#DC2626',
      errorSubtle: '#FAE4E4',
      info: '#0EA5E9',
      infoSubtle: '#E2F4FC',
    },
    border: {
      default: '#FED7AA',
      subtle: '#FFEDD5',
      focus: '#F97316',
      hover: '#E4C199',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#F97316',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#F97316',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(67, 20, 7, 0.5)',
      tooltip: '#431407',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#1C0C05',
      secondary: '#431407',
      card: '#9A3412',
      sidebar: '#0C0502',
      elevated: '#9A3412',
      hover: '#271811',
      active: '#32241E',
    },
    text: {
      primary: '#FFF7ED',
      secondary: '#FED7AA',
      muted: '#FB923C',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#FB923C',
      secondary: '#FDBA74',
      tertiary: '#FED7AA',
      hover: '#FB9F53',
      active: '#FBA763',
    },
    status: {
      success: '#4ADE80',
      successSubtle: '#E9FBEF',
      warning: '#FACC15',
      warningSubtle: '#FEF8E2',
      error: '#F87171',
      errorSubtle: '#FEEDED',
      info: '#38BDF8',
      infoSubtle: '#E7F7FE',
    },
    border: {
      default: '#C2410C',
      subtle: '#9A3412',
      focus: '#FB923C',
      hover: '#C85424',
    },
    interactive: {
      default: '#271811',
      hover: '#32241E',
      active: '#3E302A',
      disabled: '#1C0C05',
      focus: '#FB923C',
    },
    input: {
      bg: '#9A3412',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#FB923C',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(28, 12, 5, 0.75)',
      tooltip: '#1F2937',
      popover: '#32241E',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#F97316', '#FB923C', '#FDBA74', '#22C55E', '#EAB308'], positive: '#22C55E', negative: '#DC2626' },
};

export const snowTheme: VisualTheme = {
  id: 'snow',
  name: 'Snow',
  description: 'Pure, clean white with subtle grays',
  category: 'light',
  light: {
    bg: {
      primary: '#FAFBFC',
      secondary: '#F4F5F6',
      card: '#FFFFFF',
      sidebar: '#2C3E50',
      elevated: '#FFFFFF',
      hover: '#F2F3F4',
      active: '#EBEBEC',
    },
    text: {
      primary: '#1A252F',
      secondary: '#34495E',
      muted: '#7F8C8D',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#3498DB',
      secondary: '#2980B9',
      tertiary: '#5DADE2',
      hover: '#2D85C0',
      active: '#2979AF',
    },
    status: {
      success: '#27AE60',
      successSubtle: '#E5F5EB',
      warning: '#F39C12',
      warningSubtle: '#FDF3E2',
      error: '#E74C3C',
      errorSubtle: '#FCE9E7',
      info: '#3498DB',
      infoSubtle: '#E6F2FA',
    },
    border: {
      default: '#E1E5E9',
      subtle: '#F4F5F6',
      focus: '#3498DB',
      hover: '#CACED1',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#3498DB',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#3498DB',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(26, 37, 47, 0.5)',
      tooltip: '#1A252F',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#1A252F',
      secondary: '#2C3E50',
      card: '#34495E',
      sidebar: '#0D1318',
      elevated: '#34495E',
      hover: '#252F39',
      active: '#303A43',
    },
    text: {
      primary: '#FAFBFC',
      secondary: '#BDC3C7',
      muted: '#7F8C8D',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#5DADE2',
      secondary: '#85C1E9',
      tertiary: '#AED6F1',
      hover: '#70B6E5',
      active: '#7DBDE7',
    },
    status: {
      success: '#58D68D',
      successSubtle: '#EAFAF1',
      warning: '#F5B041',
      warningSubtle: '#FDF5E8',
      error: '#EC7063',
      errorSubtle: '#FCEDEC',
      info: '#5DADE2',
      infoSubtle: '#EBF5FB',
    },
    border: {
      default: '#5D6D7E',
      subtle: '#34495E',
      focus: '#5DADE2',
      hover: '#6D7B8A',
    },
    interactive: {
      default: '#252F39',
      hover: '#303A43',
      active: '#3C454E',
      disabled: '#1A252F',
      focus: '#5DADE2',
    },
    input: {
      bg: '#34495E',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#5DADE2',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(26, 37, 47, 0.75)',
      tooltip: '#1F2937',
      popover: '#303A43',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#3498DB', '#27AE60', '#9B59B6', '#F39C12', '#E74C3C'], positive: '#27AE60', negative: '#E74C3C' },
};

export const sepiaTheme: VisualTheme = {
  id: 'sepia',
  name: 'Sepia',
  description: 'Warm, nostalgic sepia tones',
  category: 'light',
  light: {
    bg: {
      primary: '#FAF5E9',
      secondary: '#F0E6D2',
      card: '#FFFFFF',
      sidebar: '#5D4E37',
      elevated: '#FFFFFF',
      hover: '#F2EDE2',
      active: '#EBE6DB',
    },
    text: {
      primary: '#3D2E17',
      secondary: '#5D4E37',
      muted: '#8D7E67',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#8B4513',
      secondary: '#A0522D',
      tertiary: '#CD853F',
      hover: '#7A3C10',
      active: '#6F370F',
    },
    status: {
      success: '#6B8E23',
      successSubtle: '#EDF1E4',
      warning: '#DAA520',
      warningSubtle: '#FAF4E4',
      error: '#B22222',
      errorSubtle: '#F5E4E4',
      info: '#4169E1',
      infoSubtle: '#E8EDFB',
    },
    border: {
      default: '#DDD4C0',
      subtle: '#F0E6D2',
      focus: '#8B4513',
      hover: '#C6BEAC',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#8B4513',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#8B4513',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(61, 46, 23, 0.5)',
      tooltip: '#3D2E17',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#2D2013',
      secondary: '#3D3023',
      card: '#4D4033',
      sidebar: '#1D1008',
      elevated: '#4D4033',
      hover: '#372B1E',
      active: '#42362A',
    },
    text: {
      primary: '#FAF5E9',
      secondary: '#DDD4C0',
      muted: '#8D7E67',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#CD853F',
      secondary: '#DEB887',
      tertiary: '#F5DEB3',
      hover: '#D39356',
      active: '#D79D65',
    },
    status: {
      success: '#9ACD32',
      successSubtle: '#F2F9E6',
      warning: '#FFD700',
      warningSubtle: '#FFFAE0',
      error: '#FA8072',
      errorSubtle: '#FEEFEE',
      info: '#87CEEB',
      infoSubtle: '#F0F9FC',
    },
    border: {
      default: '#5D4E37',
      subtle: '#4D4033',
      focus: '#CD853F',
      hover: '#6D5F4B',
    },
    interactive: {
      default: '#372B1E',
      hover: '#42362A',
      active: '#4C4136',
      disabled: '#2D2013',
      focus: '#CD853F',
    },
    input: {
      bg: '#4D4033',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#CD853F',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(45, 32, 19, 0.75)',
      tooltip: '#1F2937',
      popover: '#42362A',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#8B4513', '#A0522D', '#CD853F', '#6B8E23', '#DAA520'], positive: '#6B8E23', negative: '#B22222' },
};

export const nordLightTheme: VisualTheme = {
  id: 'nordlight',
  name: 'Nord Light',
  description: 'Arctic light palette from Nord',
  category: 'light',
  light: {
    bg: {
      primary: '#ECEFF4',
      secondary: '#E5E9F0',
      card: '#FFFFFF',
      sidebar: '#3B4252',
      elevated: '#FFFFFF',
      hover: '#E4E7EC',
      active: '#DDE0E5',
    },
    text: {
      primary: '#2E3440',
      secondary: '#4C566A',
      muted: '#7B88A1',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#5E81AC',
      secondary: '#81A1C1',
      tertiary: '#88C0D0',
      hover: '#527197',
      active: '#4B6789',
    },
    status: {
      success: '#A3BE8C',
      successSubtle: '#F3F7F1',
      warning: '#EBCB8B',
      warningSubtle: '#FCF8F1',
      error: '#BF616A',
      errorSubtle: '#F7ECED',
      info: '#88C0D0',
      infoSubtle: '#F0F7F9',
    },
    border: {
      default: '#D8DEE9',
      subtle: '#E5E9F0',
      focus: '#5E81AC',
      hover: '#C2C7D1',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#5E81AC',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#5E81AC',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(46, 52, 64, 0.5)',
      tooltip: '#2E3440',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#2E3440',
      secondary: '#3B4252',
      card: '#434C5E',
      sidebar: '#242933',
      elevated: '#434C5E',
      hover: '#383E49',
      active: '#424853',
    },
    text: {
      primary: '#ECEFF4',
      secondary: '#D8DEE9',
      muted: '#7B88A1',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#5E81AC',
      secondary: '#81A1C1',
      tertiary: '#88C0D0',
      hover: '#7190B5',
      active: '#7E9ABC',
    },
    status: {
      success: '#A3BE8C',
      successSubtle: '#F3F7F1',
      warning: '#EBCB8B',
      warningSubtle: '#FCF8F1',
      error: '#BF616A',
      errorSubtle: '#F7ECED',
      info: '#88C0D0',
      infoSubtle: '#F0F7F9',
    },
    border: {
      default: '#4C566A',
      subtle: '#434C5E',
      focus: '#5E81AC',
      hover: '#5D6678',
    },
    interactive: {
      default: '#383E49',
      hover: '#424853',
      active: '#4D525C',
      disabled: '#2E3440',
      focus: '#5E81AC',
    },
    input: {
      bg: '#434C5E',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#5E81AC',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(46, 52, 64, 0.75)',
      tooltip: '#1F2937',
      popover: '#424853',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#5E81AC', '#81A1C1', '#88C0D0', '#A3BE8C', '#EBCB8B'], positive: '#A3BE8C', negative: '#BF616A' },
};

export const gruvboxLightTheme: VisualTheme = {
  id: 'gruvboxlight',
  name: 'Gruvbox Light',
  description: 'Retro groove with light background',
  category: 'light',
  light: {
    bg: {
      primary: '#FBF1C7',
      secondary: '#EBDBB2',
      card: '#FFFFFF',
      sidebar: '#504945',
      elevated: '#FFFFFF',
      hover: '#F3E9C1',
      active: '#EBE2BB',
    },
    text: {
      primary: '#3C3836',
      secondary: '#504945',
      muted: '#7C6F64',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#D65D0E',
      secondary: '#458588',
      tertiary: '#98971A',
      hover: '#BC510C',
      active: '#AB4A0B',
    },
    status: {
      success: '#98971A',
      successSubtle: '#F2F2E3',
      warning: '#D79921',
      warningSubtle: '#FAF2E4',
      error: '#CC241D',
      errorSubtle: '#F8E4E3',
      info: '#458588',
      infoSubtle: '#E8F0F0',
    },
    border: {
      default: '#D5C4A1',
      subtle: '#EBDBB2',
      focus: '#D65D0E',
      hover: '#BFB090',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#D65D0E',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#D65D0E',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(60, 56, 54, 0.5)',
      tooltip: '#3C3836',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#282828',
      secondary: '#3C3836',
      card: '#504945',
      sidebar: '#1D2021',
      elevated: '#504945',
      hover: '#323232',
      active: '#3D3D3D',
    },
    text: {
      primary: '#EBDBB2',
      secondary: '#D5C4A1',
      muted: '#928374',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#FE8019',
      secondary: '#83A598',
      tertiary: '#B8BB26',
      hover: '#FE8F34',
      active: '#FE9947',
    },
    status: {
      success: '#B8BB26',
      successSubtle: '#F6F6E4',
      warning: '#FABD2F',
      warningSubtle: '#FEF7E6',
      error: '#FB4934',
      errorSubtle: '#FEE9E6',
      info: '#83A598',
      infoSubtle: '#F0F4F2',
    },
    border: {
      default: '#504945',
      subtle: '#3C3836',
      focus: '#FE8019',
      hover: '#615B57',
    },
    interactive: {
      default: '#323232',
      hover: '#3D3D3D',
      active: '#484848',
      disabled: '#282828',
      focus: '#FE8019',
    },
    input: {
      bg: '#504945',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#FE8019',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(40, 40, 40, 0.75)',
      tooltip: '#1F2937',
      popover: '#3D3D3D',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#D65D0E', '#458588', '#98971A', '#D79921', '#CC241D'], positive: '#98971A', negative: '#CC241D' },
};

export const blossomTheme: VisualTheme = {
  id: 'blossom',
  name: 'Blossom',
  description: 'Cherry blossom inspired palette',
  category: 'light',
  light: {
    bg: {
      primary: '#FFF0F5',
      secondary: '#FFE4EC',
      card: '#FFFFFF',
      sidebar: '#C71585',
      elevated: '#FFFFFF',
      hover: '#F7E8ED',
      active: '#EFE1E6',
    },
    text: {
      primary: '#4A1C3C',
      secondary: '#7A3C5C',
      muted: '#AA6C8C',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#DB7093',
      secondary: '#FF69B4',
      tertiary: '#FFB6C1',
      hover: '#C06281',
      active: '#AF5975',
    },
    status: {
      success: '#3CB371',
      successSubtle: '#E7F5ED',
      warning: '#FFD700',
      warningSubtle: '#FFFAE0',
      error: '#FF6347',
      errorSubtle: '#FFECE8',
      info: '#87CEEB',
      infoSubtle: '#F0F9FC',
    },
    border: {
      default: '#FFD0E0',
      subtle: '#FFE4EC',
      focus: '#DB7093',
      hover: '#E5BBC9',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#DB7093',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#DB7093',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(74, 28, 60, 0.5)',
      tooltip: '#4A1C3C',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#2A0A1C',
      secondary: '#3A1A2C',
      card: '#4A2A3C',
      sidebar: '#1A0010',
      elevated: '#4A2A3C',
      hover: '#341627',
      active: '#3F2232',
    },
    text: {
      primary: '#FFF0F5',
      secondary: '#FFD0E0',
      muted: '#AA6C8C',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#FF69B4',
      secondary: '#FFB6C1',
      tertiary: '#FFC0CB',
      hover: '#FF7BBD',
      active: '#FF87C3',
    },
    status: {
      success: '#98FB98',
      successSubtle: '#F2FEF2',
      warning: '#FFD700',
      warningSubtle: '#FFFAE0',
      error: '#FF6B6B',
      errorSubtle: '#FFEDED',
      info: '#87CEEB',
      infoSubtle: '#F0F9FC',
    },
    border: {
      default: '#7A3C5C',
      subtle: '#4A2A3C',
      focus: '#FF69B4',
      hover: '#874F6C',
    },
    interactive: {
      default: '#341627',
      hover: '#3F2232',
      active: '#492E3E',
      disabled: '#2A0A1C',
      focus: '#FF69B4',
    },
    input: {
      bg: '#4A2A3C',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#FF69B4',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(42, 10, 28, 0.75)',
      tooltip: '#1F2937',
      popover: '#3F2232',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#DB7093', '#FF69B4', '#FFB6C1', '#3CB371', '#FFD700'], positive: '#3CB371', negative: '#FF6347' },
};

export const sandTheme: VisualTheme = {
  id: 'sand',
  name: 'Sand',
  description: 'Warm desert sand palette',
  category: 'light',
  light: {
    bg: {
      primary: '#FAF8F5',
      secondary: '#F0ECE3',
      card: '#FFFFFF',
      sidebar: '#8B7355',
      elevated: '#FFFFFF',
      hover: '#F2F0ED',
      active: '#EBE9E6',
    },
    text: {
      primary: '#3D352A',
      secondary: '#6B5D4D',
      muted: '#A99C8A',
      disabled: '#D1D5DB',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#C2956E',
      secondary: '#D4A574',
      tertiary: '#E6C9A8',
      hover: '#AA8360',
      active: '#9B7758',
    },
    status: {
      success: '#7A9D54',
      successSubtle: '#EFF3EA',
      warning: '#D4A017',
      warningSubtle: '#F9F3E3',
      error: '#C9544E',
      errorSubtle: '#F8EAE9',
      info: '#5B8BA0',
      infoSubtle: '#EBF1F3',
    },
    border: {
      default: '#E0D8CC',
      subtle: '#F0ECE3',
      focus: '#C2956E',
      hover: '#C9C2B7',
    },
    interactive: {
      default: '#F9FAFB',
      hover: '#F3F4F6',
      active: '#E5E7EB',
      disabled: '#F9FAFB',
      focus: '#C2956E',
    },
    input: {
      bg: '#FFFFFF',
      border: '#D1D5DB',
      borderHover: '#9CA3AF',
      borderFocus: '#C2956E',
      placeholder: '#9CA3AF',
      bgDisabled: '#F9FAFB',
    },
    overlay: {
      backdrop: 'rgba(61, 53, 42, 0.5)',
      tooltip: '#3D352A',
      popover: '#FFFFFF',
    },
  },
  dark: {
    bg: {
      primary: '#2A2520',
      secondary: '#3D352A',
      card: '#4D453A',
      sidebar: '#1A1510',
      elevated: '#4D453A',
      hover: '#342F2B',
      active: '#3F3A36',
    },
    text: {
      primary: '#FAF8F5',
      secondary: '#E0D8CC',
      muted: '#A99C8A',
      disabled: '#6B7280',
      onAccent: '#FFFFFF',
    },
    accent: {
      primary: '#D4A574',
      secondary: '#E6C9A8',
      tertiary: '#F5E6D3',
      hover: '#D9AF84',
      active: '#DCB78F',
    },
    status: {
      success: '#A4C97A',
      successSubtle: '#F4F8EF',
      warning: '#F0C040',
      warningSubtle: '#FDF7E8',
      error: '#E07A74',
      errorSubtle: '#FBEFEE',
      info: '#8BB8CA',
      infoSubtle: '#F1F6F8',
    },
    border: {
      default: '#6B5D4D',
      subtle: '#4D453A',
      focus: '#D4A574',
      hover: '#796D5E',
    },
    interactive: {
      default: '#342F2B',
      hover: '#3F3A36',
      active: '#494541',
      disabled: '#2A2520',
      focus: '#D4A574',
    },
    input: {
      bg: '#4D453A',
      border: '#4B5563',
      borderHover: '#6B7280',
      borderFocus: '#D4A574',
      placeholder: '#6B7280',
      bgDisabled: '#1F2937',
    },
    overlay: {
      backdrop: 'rgba(42, 37, 32, 0.75)',
      tooltip: '#1F2937',
      popover: '#3F3A36',
    },
  },
  typography: sharedTypography,
  spacing: sharedSpacing,
  borderRadius: sharedBorderRadius,
  shadows: sharedShadows,
  chart: { colors: ['#C2956E', '#7A9D54', '#5B8BA0', '#D4A017', '#C9544E'], positive: '#7A9D54', negative: '#C9544E' },
};

// Export all tweakcn themes as an array
export const tweakcnThemes: VisualTheme[] = [
  // Dark themes
  draculaTheme,
  nordTheme,
  tokyoNightTheme,
  monokaiTheme,
  solarizedDarkTheme,
  gruvboxTheme,
  catppuccinTheme,
  oneDarkTheme,
  synthwaveTheme,
  forestTheme,
  oceanTheme,
  retroTheme,
  // Light themes
  creamTheme,
  solarizedLightTheme,
  githubTheme,
  paperTheme,
  roseTheme,
  mintTheme,
  lavenderTheme,
  skyTheme,
  peachTheme,
  snowTheme,
  sepiaTheme,
  nordLightTheme,
  gruvboxLightTheme,
  blossomTheme,
  sandTheme,
];

// Export themes grouped by category
export const tweakcnDarkThemes = tweakcnThemes.filter(t => t.category === 'dark');
export const tweakcnLightThemes = tweakcnThemes.filter(t => t.category === 'light');
