-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.access_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  contact_id uuid NOT NULL,
  code text NOT NULL UNIQUE,
  code_type USER-DEFINED NOT NULL DEFAULT 'permanent'::access_code_type,
  valid_from timestamp with time zone NOT NULL DEFAULT now(),
  valid_until timestamp with time zone,
  max_uses integer,
  current_uses integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  revoked_at timestamp with time zone,
  revoked_by uuid,
  CONSTRAINT access_codes_pkey PRIMARY KEY (id),
  CONSTRAINT access_codes_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.security_contacts(id),
  CONSTRAINT access_codes_revoked_by_fkey FOREIGN KEY (revoked_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.access_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  access_code_id uuid,
  contact_id uuid NOT NULL,
  resident_id uuid NOT NULL,
  check_in_time timestamp with time zone NOT NULL DEFAULT now(),
  check_out_time timestamp with time zone,
  verified_by uuid,
  gate_location text,
  notes text,
  flagged boolean NOT NULL DEFAULT false,
  flag_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT access_logs_pkey PRIMARY KEY (id),
  CONSTRAINT access_logs_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.security_contacts(id),
  CONSTRAINT access_logs_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT access_logs_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id),
  CONSTRAINT access_logs_access_code_id_fkey FOREIGN KEY (access_code_id) REFERENCES public.access_codes(id)
);
CREATE TABLE public.announcement_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  icon text,
  color text DEFAULT 'blue'::text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT announcement_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.announcement_read_receipts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  announcement_id uuid NOT NULL,
  resident_id uuid NOT NULL,
  read_at timestamp with time zone DEFAULT now(),
  CONSTRAINT announcement_read_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT announcement_read_receipts_announcement_id_fkey FOREIGN KEY (announcement_id) REFERENCES public.announcements(id),
  CONSTRAINT announcement_read_receipts_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id)
);
CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  summary text,
  category_id uuid,
  status USER-DEFINED DEFAULT 'draft'::announcement_status,
  priority USER-DEFINED DEFAULT 'normal'::announcement_priority,
  target_audience USER-DEFINED DEFAULT 'all'::target_audience,
  target_houses ARRAY,
  is_pinned boolean DEFAULT false,
  published_at timestamp with time zone,
  scheduled_for timestamp with time zone,
  expires_at timestamp with time zone,
  attachment_urls ARRAY,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.announcement_categories(id),
  CONSTRAINT announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT announcements_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.app_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  display_name character varying NOT NULL,
  description text,
  category USER-DEFINED NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT app_permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.app_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  display_name character varying NOT NULL,
  description text,
  category character varying DEFAULT 'exco'::character varying,
  level integer DEFAULT 0,
  is_system_role boolean DEFAULT false,
  is_active boolean DEFAULT true,
  can_be_assigned_to_resident boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  requires_contact_verification boolean NOT NULL DEFAULT false,
  CONSTRAINT app_roles_pkey PRIMARY KEY (id),
  CONSTRAINT app_roles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.approval_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  request_type USER-DEFINED NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  requested_changes jsonb NOT NULL,
  current_values jsonb NOT NULL,
  reason text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::approval_status CHECK (status = ANY (ARRAY['pending'::approval_status, 'approved'::approval_status, 'rejected'::approval_status])),
  requested_by uuid NOT NULL,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  notification_sent_at timestamp with time zone,
  reminder_sent_at timestamp with time zone,
  affected_resident_id uuid,
  affected_house_id uuid,
  CONSTRAINT approval_requests_pkey PRIMARY KEY (id),
  CONSTRAINT approval_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id),
  CONSTRAINT approval_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id),
  CONSTRAINT approval_requests_affected_resident_id_fkey FOREIGN KEY (affected_resident_id) REFERENCES public.residents(id),
  CONSTRAINT approval_requests_affected_house_id_fkey FOREIGN KEY (affected_house_id) REFERENCES public.houses(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid,
  action USER-DEFINED NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  entity_display text,
  old_values jsonb,
  new_values jsonb,
  description text,
  metadata jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.bank_statement_imports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_name text NOT NULL,
  file_type text NOT NULL CHECK (file_type = ANY (ARRAY['csv'::text, 'xlsx'::text])),
  bank_account_id uuid,
  bank_name text DEFAULT 'FirstBank'::text,
  transaction_filter text DEFAULT 'credit'::text CHECK (transaction_filter = ANY (ARRAY['credit'::text, 'debit'::text, 'all'::text])),
  total_rows integer NOT NULL DEFAULT 0,
  matched_rows integer DEFAULT 0,
  created_rows integer DEFAULT 0,
  skipped_rows integer DEFAULT 0,
  error_rows integer DEFAULT 0,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'awaiting_approval'::text, 'approved'::text, 'completed'::text, 'failed'::text, 'rejected'::text])),
  column_mapping jsonb,
  import_summary jsonb,
  created_by uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT bank_statement_imports_pkey PRIMARY KEY (id),
  CONSTRAINT bank_statement_imports_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.estate_bank_accounts(id),
  CONSTRAINT bank_statement_imports_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT bank_statement_imports_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.bank_statement_rows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  import_id uuid NOT NULL,
  row_number integer NOT NULL,
  raw_data jsonb NOT NULL,
  transaction_date date,
  description text,
  amount numeric,
  transaction_type text CHECK (transaction_type = ANY (ARRAY['credit'::text, 'debit'::text])),
  reference text,
  matched_resident_id uuid,
  match_confidence text CHECK (match_confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text, 'none'::text, 'manual'::text])),
  match_method text CHECK (match_method = ANY (ARRAY['alias'::text, 'phone'::text, 'name'::text, 'house_number'::text, 'manual'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'matched'::text, 'unmatched'::text, 'duplicate'::text, 'created'::text, 'skipped'::text, 'error'::text])),
  payment_id uuid,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  tag_id uuid,
  tagged_by uuid,
  tagged_at timestamp with time zone,
  auto_tagged boolean DEFAULT false,
  CONSTRAINT bank_statement_rows_pkey PRIMARY KEY (id),
  CONSTRAINT bank_statement_rows_import_id_fkey FOREIGN KEY (import_id) REFERENCES public.bank_statement_imports(id),
  CONSTRAINT bank_statement_rows_matched_resident_id_fkey FOREIGN KEY (matched_resident_id) REFERENCES public.residents(id),
  CONSTRAINT bank_statement_rows_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payment_records(id),
  CONSTRAINT bank_statement_rows_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.transaction_tags(id),
  CONSTRAINT bank_statement_rows_tagged_by_fkey FOREIGN KEY (tagged_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.billing_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  billing_profile_id uuid NOT NULL,
  name text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  frequency USER-DEFINED NOT NULL DEFAULT 'monthly'::billing_frequency,
  is_mandatory boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT billing_items_pkey PRIMARY KEY (id),
  CONSTRAINT billing_items_billing_profile_id_fkey FOREIGN KEY (billing_profile_id) REFERENCES public.billing_profiles(id)
);
CREATE TABLE public.billing_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  target_type USER-DEFINED NOT NULL DEFAULT 'house'::billing_target_type,
  applicable_roles ARRAY,
  is_one_time boolean NOT NULL DEFAULT false,
  effective_date date NOT NULL DEFAULT CURRENT_DATE,
  is_development_levy boolean DEFAULT false,
  CONSTRAINT billing_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT billing_profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.document_access_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  accessed_by uuid NOT NULL,
  action character varying NOT NULL,
  ip_address inet,
  user_agent text,
  accessed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_access_logs_pkey PRIMARY KEY (id),
  CONSTRAINT document_access_logs_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT document_access_logs_accessed_by_fkey FOREIGN KEY (accessed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.document_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  is_resident_accessible boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT document_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text,
  file_name character varying NOT NULL,
  file_path character varying NOT NULL,
  file_type character varying,
  file_size_bytes bigint,
  mime_type character varying,
  category_id uuid,
  resident_id uuid,
  house_id uuid,
  version integer DEFAULT 1,
  parent_document_id uuid,
  uploaded_by uuid NOT NULL,
  is_archived boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT documents_house_id_fkey FOREIGN KEY (house_id) REFERENCES public.houses(id),
  CONSTRAINT documents_parent_document_id_fkey FOREIGN KEY (parent_document_id) REFERENCES public.documents(id),
  CONSTRAINT documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id),
  CONSTRAINT documents_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.document_categories(id),
  CONSTRAINT documents_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id)
);
CREATE TABLE public.email_imports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_email text NOT NULL,
  bank_name text NOT NULL DEFAULT 'First Bank'::text,
  trigger_type USER-DEFINED NOT NULL,
  emails_fetched integer NOT NULL DEFAULT 0,
  emails_parsed integer NOT NULL DEFAULT 0,
  emails_skipped integer NOT NULL DEFAULT 0,
  emails_errored integer NOT NULL DEFAULT 0,
  transactions_extracted integer NOT NULL DEFAULT 0,
  transactions_matched integer NOT NULL DEFAULT 0,
  transactions_auto_processed integer NOT NULL DEFAULT 0,
  transactions_queued integer NOT NULL DEFAULT 0,
  transactions_skipped integer NOT NULL DEFAULT 0,
  transactions_errored integer NOT NULL DEFAULT 0,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::email_import_status,
  error_message text,
  import_summary jsonb,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT email_imports_pkey PRIMARY KEY (id),
  CONSTRAINT email_imports_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.email_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_email text NOT NULL,
  recipient_name text,
  resident_id uuid,
  email_type text NOT NULL,
  subject text NOT NULL,
  resend_id text,
  status text DEFAULT 'pending'::text,
  error_message text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_logs_pkey PRIMARY KEY (id),
  CONSTRAINT email_logs_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id)
);
CREATE TABLE public.email_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email_import_id uuid NOT NULL,
  gmail_message_id text NOT NULL,
  gmail_thread_id text,
  subject text,
  from_address text,
  to_address text,
  received_at timestamp with time zone,
  email_type USER-DEFINED NOT NULL DEFAULT 'unknown'::email_message_type,
  raw_content_path text,
  attachments jsonb DEFAULT '[]'::jsonb,
  processing_status USER-DEFINED NOT NULL DEFAULT 'pending'::email_processing_status,
  processing_error text,
  transactions_extracted integer NOT NULL DEFAULT 0,
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT email_messages_pkey PRIMARY KEY (id),
  CONSTRAINT email_messages_email_import_id_fkey FOREIGN KEY (email_import_id) REFERENCES public.email_imports(id)
);
CREATE TABLE public.email_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email_message_id uuid NOT NULL,
  email_import_id uuid NOT NULL,
  transaction_date date,
  description text,
  amount numeric,
  transaction_type text CHECK (transaction_type = ANY (ARRAY['credit'::text, 'debit'::text])),
  reference text,
  bank_account_last4 text,
  raw_extracted_data jsonb,
  matched_resident_id uuid,
  match_confidence text CHECK (match_confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text, 'none'::text, 'manual'::text])),
  match_method text CHECK (match_method = ANY (ARRAY['alias'::text, 'phone'::text, 'name'::text, 'house_number'::text, 'manual'::text])),
  match_details jsonb,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::email_transaction_status,
  payment_id uuid,
  skip_reason text,
  error_message text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  matched_at timestamp with time zone,
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT email_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT email_transactions_email_message_id_fkey FOREIGN KEY (email_message_id) REFERENCES public.email_messages(id),
  CONSTRAINT email_transactions_email_import_id_fkey FOREIGN KEY (email_import_id) REFERENCES public.email_imports(id),
  CONSTRAINT email_transactions_matched_resident_id_fkey FOREIGN KEY (matched_resident_id) REFERENCES public.residents(id),
  CONSTRAINT email_transactions_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payment_records(id),
  CONSTRAINT email_transactions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.entity_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type USER-DEFINED NOT NULL,
  entity_id uuid NOT NULL,
  title text,
  content text NOT NULL,
  category USER-DEFINED NOT NULL DEFAULT 'general'::note_category,
  is_confidential boolean NOT NULL DEFAULT false,
  confidential_roles ARRAY,
  document_id uuid,
  version integer NOT NULL DEFAULT 1,
  parent_note_id uuid,
  is_current boolean NOT NULL DEFAULT true,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entity_notes_pkey PRIMARY KEY (id),
  CONSTRAINT entity_notes_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT entity_notes_parent_note_id_fkey FOREIGN KEY (parent_note_id) REFERENCES public.entity_notes(id),
  CONSTRAINT entity_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.escalation_states (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  resident_id uuid NOT NULL,
  current_level integer NOT NULL DEFAULT 0,
  last_notification_id uuid,
  last_notified_at timestamp with time zone,
  next_scheduled_at timestamp with time zone,
  is_resolved boolean NOT NULL DEFAULT false,
  resolved_at timestamp with time zone,
  resolved_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT escalation_states_pkey PRIMARY KEY (id),
  CONSTRAINT escalation_states_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT escalation_states_last_notification_id_fkey FOREIGN KEY (last_notification_id) REFERENCES public.notification_history(id)
);
CREATE TABLE public.estate_bank_account_passwords (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bank_account_id uuid NOT NULL UNIQUE,
  password_encrypted text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  CONSTRAINT estate_bank_account_passwords_pkey PRIMARY KEY (id),
  CONSTRAINT estate_bank_account_passwords_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.estate_bank_accounts(id),
  CONSTRAINT estate_bank_account_passwords_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.estate_bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_number text NOT NULL UNIQUE,
  account_name text NOT NULL,
  bank_name text NOT NULL DEFAULT 'FirstBank'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  description text,
  CONSTRAINT estate_bank_accounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.generated_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  report_type text NOT NULL CHECK (report_type = ANY (ARRAY['financial_overview'::text, 'collection_report'::text, 'invoice_aging'::text, 'transaction_log'::text])),
  schedule_id uuid,
  period_start date NOT NULL,
  period_end date NOT NULL,
  period_preset text,
  bank_account_ids ARRAY,
  template_style text DEFAULT 'modern'::text,
  report_data jsonb NOT NULL,
  summary jsonb,
  generation_trigger text NOT NULL CHECK (generation_trigger = ANY (ARRAY['manual'::text, 'scheduled'::text, 'api'::text])),
  generation_duration_ms integer,
  generated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  version integer DEFAULT 1,
  parent_report_id uuid,
  is_latest boolean DEFAULT true,
  edit_notes text,
  CONSTRAINT generated_reports_pkey PRIMARY KEY (id),
  CONSTRAINT generated_reports_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.report_schedules(id),
  CONSTRAINT generated_reports_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES auth.users(id),
  CONSTRAINT generated_reports_parent_report_id_fkey FOREIGN KEY (parent_report_id) REFERENCES public.generated_reports(id)
);
CREATE TABLE public.gmail_oauth_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email_address text NOT NULL,
  access_token_encrypted text NOT NULL,
  refresh_token_encrypted text NOT NULL,
  token_expiry timestamp with time zone NOT NULL,
  scopes ARRAY NOT NULL DEFAULT ARRAY['https://www.googleapis.com/auth/gmail.readonly'::text],
  is_active boolean NOT NULL DEFAULT true,
  last_sync_at timestamp with time zone,
  last_sync_status text CHECK (last_sync_status = ANY (ARRAY['success'::text, 'error'::text, 'partial'::text])),
  last_sync_message text,
  last_sync_emails_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT gmail_oauth_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT gmail_oauth_credentials_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.hierarchical_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setting_key text NOT NULL,
  category text NOT NULL DEFAULT 'general'::text,
  level USER-DEFINED NOT NULL,
  house_id uuid,
  resident_id uuid,
  value jsonb NOT NULL,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT hierarchical_settings_pkey PRIMARY KEY (id),
  CONSTRAINT hierarchical_settings_house_id_fkey FOREIGN KEY (house_id) REFERENCES public.houses(id),
  CONSTRAINT hierarchical_settings_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT hierarchical_settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT hierarchical_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.house_levy_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  house_id uuid NOT NULL,
  billing_profile_id uuid NOT NULL,
  resident_id uuid NOT NULL,
  invoice_id uuid,
  applied_at timestamp with time zone DEFAULT now(),
  applied_by uuid,
  notes text,
  CONSTRAINT house_levy_history_pkey PRIMARY KEY (id),
  CONSTRAINT house_levy_history_house_id_fkey FOREIGN KEY (house_id) REFERENCES public.houses(id),
  CONSTRAINT house_levy_history_billing_profile_id_fkey FOREIGN KEY (billing_profile_id) REFERENCES public.billing_profiles(id),
  CONSTRAINT house_levy_history_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT house_levy_history_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT house_levy_history_applied_by_fkey FOREIGN KEY (applied_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.house_ownership_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  house_id uuid NOT NULL,
  resident_id uuid,
  resident_role USER-DEFINED,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['house_added'::text, 'ownership_start'::text, 'ownership_transfer'::text, 'ownership_end'::text, 'move_in'::text, 'move_out'::text, 'role_change'::text])),
  previous_role USER-DEFINED,
  event_date date NOT NULL DEFAULT CURRENT_DATE,
  notes text,
  is_current boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT house_ownership_history_pkey PRIMARY KEY (id),
  CONSTRAINT house_ownership_history_house_id_fkey FOREIGN KEY (house_id) REFERENCES public.houses(id),
  CONSTRAINT house_ownership_history_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT house_ownership_history_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.house_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  max_residents integer NOT NULL DEFAULT 10,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  billing_profile_id uuid,
  CONSTRAINT house_types_pkey PRIMARY KEY (id),
  CONSTRAINT house_types_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT house_types_billing_profile_id_fkey FOREIGN KEY (billing_profile_id) REFERENCES public.billing_profiles(id)
);
CREATE TABLE public.houses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  house_number text NOT NULL,
  street_id uuid NOT NULL,
  house_type_id uuid,
  address_line_2 text,
  is_occupied boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  billing_profile_id uuid,
  number_of_plots integer NOT NULL DEFAULT 1 CHECK (number_of_plots >= 1),
  short_name text,
  CONSTRAINT houses_pkey PRIMARY KEY (id),
  CONSTRAINT houses_street_id_fkey FOREIGN KEY (street_id) REFERENCES public.streets(id),
  CONSTRAINT houses_house_type_id_fkey FOREIGN KEY (house_type_id) REFERENCES public.house_types(id),
  CONSTRAINT houses_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT houses_billing_profile_id_fkey FOREIGN KEY (billing_profile_id) REFERENCES public.billing_profiles(id)
);
CREATE TABLE public.impersonation_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  admin_profile_id uuid NOT NULL,
  impersonated_resident_id uuid NOT NULL,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  session_type text NOT NULL DEFAULT 'direct'::text CHECK (session_type = ANY (ARRAY['direct'::text, 'approved'::text])),
  approval_request_id uuid,
  page_views jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT impersonation_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT impersonation_sessions_admin_profile_id_fkey FOREIGN KEY (admin_profile_id) REFERENCES public.profiles(id),
  CONSTRAINT impersonation_sessions_impersonated_resident_id_fkey FOREIGN KEY (impersonated_resident_id) REFERENCES public.residents(id),
  CONSTRAINT impersonation_sessions_approval_request_id_fkey FOREIGN KEY (approval_request_id) REFERENCES public.approval_requests(id)
);
CREATE TABLE public.in_app_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_id uuid NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  icon text,
  category text NOT NULL,
  entity_type text,
  entity_id uuid,
  action_url text,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT in_app_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT in_app_notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.residents(id)
);
CREATE TABLE public.invoice_generation_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  generated_by uuid,
  trigger_type text NOT NULL CHECK (trigger_type = ANY (ARRAY['manual'::text, 'cron'::text, 'api'::text])),
  target_period date,
  generated_count integer NOT NULL DEFAULT 0,
  skipped_count integer NOT NULL DEFAULT 0,
  error_count integer NOT NULL DEFAULT 0,
  skip_reasons jsonb,
  errors jsonb,
  duration_ms integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoice_generation_log_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_generation_log_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  description text NOT NULL,
  amount numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resident_id uuid NOT NULL,
  house_id uuid,
  billing_profile_id uuid,
  invoice_number text NOT NULL UNIQUE,
  amount_due numeric NOT NULL DEFAULT 0,
  amount_paid numeric NOT NULL DEFAULT 0,
  status USER-DEFINED NOT NULL DEFAULT 'unpaid'::invoice_status,
  due_date date NOT NULL,
  period_start date,
  period_end date,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  invoice_type USER-DEFINED NOT NULL DEFAULT 'SERVICE_CHARGE'::invoice_type_enum,
  rate_snapshot jsonb,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT invoices_house_id_fkey FOREIGN KEY (house_id) REFERENCES public.houses(id),
  CONSTRAINT invoices_billing_profile_id_fkey FOREIGN KEY (billing_profile_id) REFERENCES public.billing_profiles(id),
  CONSTRAINT invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.message_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  category_id uuid,
  title_template text NOT NULL,
  content_template text NOT NULL,
  variables jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT message_templates_pkey PRIMARY KEY (id),
  CONSTRAINT message_templates_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.announcement_categories(id),
  CONSTRAINT message_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  queue_id uuid,
  template_id uuid,
  schedule_id uuid,
  recipient_id uuid,
  recipient_email text,
  recipient_phone text,
  channel text NOT NULL,
  subject text,
  body_preview text,
  status text NOT NULL CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text, 'bounced'::text, 'delivered'::text, 'opened'::text, 'clicked'::text])),
  external_id text,
  error_message text,
  metadata jsonb,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  opened_at timestamp with time zone,
  clicked_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_history_pkey PRIMARY KEY (id),
  CONSTRAINT notification_history_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.residents(id),
  CONSTRAINT notification_history_queue_id_fkey FOREIGN KEY (queue_id) REFERENCES public.notification_queue(id),
  CONSTRAINT notification_history_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.notification_templates(id),
  CONSTRAINT notification_history_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.notification_schedules(id)
);
CREATE TABLE public.notification_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resident_id uuid NOT NULL,
  category text NOT NULL,
  channel text NOT NULL DEFAULT 'email'::text,
  enabled boolean NOT NULL DEFAULT true,
  frequency text DEFAULT 'all'::text CHECK (frequency = ANY (ARRAY['all'::text, 'daily_digest'::text, 'weekly_digest'::text, 'none'::text])),
  quiet_hours_start time without time zone,
  quiet_hours_end time without time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT notification_preferences_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id)
);
CREATE TABLE public.notification_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  schedule_id uuid,
  recipient_id uuid NOT NULL,
  recipient_email text,
  recipient_phone text,
  channel text NOT NULL DEFAULT 'email'::text,
  subject text,
  body text NOT NULL,
  html_body text,
  variables jsonb,
  priority integer NOT NULL DEFAULT 5 CHECK (priority >= 1 AND priority <= 10),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'sent'::text, 'failed'::text, 'cancelled'::text])),
  deduplication_key text,
  dedup_window_minutes integer DEFAULT 1440,
  scheduled_for timestamp with time zone NOT NULL DEFAULT now(),
  attempts integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 3,
  last_attempt_at timestamp with time zone,
  sent_at timestamp with time zone,
  error_message text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT notification_queue_pkey PRIMARY KEY (id),
  CONSTRAINT notification_queue_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.notification_templates(id),
  CONSTRAINT notification_queue_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.notification_schedules(id),
  CONSTRAINT notification_queue_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.residents(id),
  CONSTRAINT notification_queue_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  template_id uuid NOT NULL,
  trigger_type text NOT NULL CHECK (trigger_type = ANY (ARRAY['days_before_due'::text, 'days_after_due'::text, 'event'::text, 'cron'::text])),
  trigger_value integer,
  cron_expression text,
  event_type text,
  escalation_sequence integer DEFAULT 0,
  parent_schedule_id uuid,
  conditions jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT notification_schedules_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.notification_templates(id),
  CONSTRAINT notification_schedules_parent_schedule_id_fkey FOREIGN KEY (parent_schedule_id) REFERENCES public.notification_schedules(id)
);
CREATE TABLE public.notification_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  display_name text NOT NULL,
  category text NOT NULL,
  channel text NOT NULL DEFAULT 'email'::text,
  subject_template text,
  body_template text NOT NULL,
  html_template text,
  variables jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id),
  CONSTRAINT notification_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.payment_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resident_id uuid NOT NULL,
  amount numeric NOT NULL,
  payment_date date NOT NULL DEFAULT CURRENT_DATE,
  period_start date,
  period_end date,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status,
  method USER-DEFINED,
  reference_number text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  import_id uuid,
  import_row_id uuid,
  house_id uuid,
  split_payment_group_id uuid,
  email_import_id uuid,
  email_transaction_id uuid,
  CONSTRAINT payment_records_pkey PRIMARY KEY (id),
  CONSTRAINT payment_records_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT payment_records_import_id_fkey FOREIGN KEY (import_id) REFERENCES public.bank_statement_imports(id),
  CONSTRAINT payment_records_import_row_id_fkey FOREIGN KEY (import_row_id) REFERENCES public.bank_statement_rows(id),
  CONSTRAINT payment_records_house_id_fkey FOREIGN KEY (house_id) REFERENCES public.houses(id),
  CONSTRAINT payment_records_email_import_id_fkey FOREIGN KEY (email_import_id) REFERENCES public.email_imports(id),
  CONSTRAINT payment_records_email_transaction_id_fkey FOREIGN KEY (email_transaction_id) REFERENCES public.email_transactions(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  full_name text NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'security_officer'::user_role,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  role_id uuid,
  resident_id uuid,
  impersonation_enabled boolean DEFAULT false,
  dashboard_theme_override text CHECK (dashboard_theme_override IS NULL OR (dashboard_theme_override = ANY (ARRAY['nahid'::text, 'paier'::text]))),
  portal_theme_override text CHECK (portal_theme_override IS NULL OR (portal_theme_override = ANY (ARRAY['nahid'::text, 'paier'::text]))),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.app_roles(id),
  CONSTRAINT profiles_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id)
);
CREATE TABLE public.report_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  report_type text NOT NULL CHECK (report_type = ANY (ARRAY['financial_overview'::text, 'collection_report'::text, 'invoice_aging'::text, 'transaction_log'::text])),
  frequency text NOT NULL CHECK (frequency = ANY (ARRAY['daily'::text, 'weekly'::text, 'monthly'::text, 'quarterly'::text, 'yearly'::text])),
  day_of_week integer CHECK (day_of_week >= 0 AND day_of_week <= 6),
  day_of_month integer CHECK (day_of_month >= 1 AND day_of_month <= 28),
  period_preset text CHECK (period_preset = ANY (ARRAY['this_month'::text, 'last_month'::text, 'this_quarter'::text, 'last_quarter'::text, 'this_year'::text, 'last_year'::text])),
  bank_account_ids ARRAY,
  include_charts boolean DEFAULT true,
  include_summary boolean DEFAULT true,
  template_style text DEFAULT 'modern'::text CHECK (template_style = ANY (ARRAY['traditional'::text, 'modern'::text])),
  is_active boolean DEFAULT true,
  last_run_at timestamp with time zone,
  next_run_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT report_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT report_schedules_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.report_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resident_id uuid NOT NULL UNIQUE,
  receive_monthly_summary boolean DEFAULT false,
  receive_quarterly_report boolean DEFAULT false,
  receive_payment_confirmation boolean DEFAULT true,
  receive_invoice_reminder boolean DEFAULT true,
  email_enabled boolean DEFAULT true,
  push_enabled boolean DEFAULT true,
  preferred_day_of_month integer DEFAULT 1 CHECK (preferred_day_of_month >= 1 AND preferred_day_of_month <= 28),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT report_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT report_subscriptions_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id)
);
CREATE TABLE public.resident_houses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resident_id uuid NOT NULL,
  house_id uuid NOT NULL,
  resident_role USER-DEFINED NOT NULL DEFAULT 'non_resident_landlord'::resident_role,
  move_in_date date NOT NULL DEFAULT CURRENT_DATE,
  move_out_date date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  sponsor_resident_id uuid,
  is_live_in boolean DEFAULT false,
  tags ARRAY DEFAULT '{}'::text[],
  is_primary boolean DEFAULT false,
  CONSTRAINT resident_houses_pkey PRIMARY KEY (id),
  CONSTRAINT resident_houses_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT resident_houses_house_id_fkey FOREIGN KEY (house_id) REFERENCES public.houses(id),
  CONSTRAINT resident_houses_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT resident_houses_sponsor_resident_id_fkey FOREIGN KEY (sponsor_resident_id) REFERENCES public.residents(id)
);
CREATE TABLE public.resident_payment_aliases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resident_id uuid NOT NULL,
  alias_name text NOT NULL,
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT resident_payment_aliases_pkey PRIMARY KEY (id),
  CONSTRAINT resident_payment_aliases_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT resident_payment_aliases_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.resident_wallets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resident_id uuid NOT NULL UNIQUE,
  balance numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT resident_wallets_pkey PRIMARY KEY (id),
  CONSTRAINT resident_wallets_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id)
);
CREATE TABLE public.residents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resident_code character NOT NULL UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text,
  phone_primary text NOT NULL,
  phone_secondary text,
  resident_type USER-DEFINED NOT NULL DEFAULT 'primary'::resident_type,
  verification_status USER-DEFINED NOT NULL DEFAULT 'pending'::verification_status,
  account_status USER-DEFINED NOT NULL DEFAULT 'active'::account_status,
  id_type text,
  id_number text,
  id_verified_at timestamp with time zone,
  id_verified_by uuid,
  photo_url text,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relationship text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  emergency_contact_resident_id uuid,
  profile_id uuid,
  entity_type USER-DEFINED NOT NULL DEFAULT 'individual'::entity_type,
  company_name character varying,
  rc_number character varying,
  liaison_contact_name character varying,
  liaison_contact_phone character varying,
  portal_enabled boolean DEFAULT false,
  portal_enabled_at timestamp with time zone,
  portal_enabled_by uuid,
  email_verified_at timestamp with time zone,
  phone_verified_at timestamp with time zone,
  CONSTRAINT residents_pkey PRIMARY KEY (id),
  CONSTRAINT residents_id_verified_by_fkey FOREIGN KEY (id_verified_by) REFERENCES public.profiles(id),
  CONSTRAINT residents_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT residents_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT residents_emergency_contact_resident_id_fkey FOREIGN KEY (emergency_contact_resident_id) REFERENCES public.residents(id),
  CONSTRAINT residents_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT residents_portal_enabled_by_fkey FOREIGN KEY (portal_enabled_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.role_assignment_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resident_role text NOT NULL,
  app_role_id uuid NOT NULL,
  is_allowed boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT role_assignment_rules_pkey PRIMARY KEY (id),
  CONSTRAINT role_assignment_rules_app_role_id_fkey FOREIGN KEY (app_role_id) REFERENCES public.app_roles(id),
  CONSTRAINT role_assignment_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.role_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.app_roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.app_permissions(id),
  CONSTRAINT role_permissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.security_contact_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  default_validity_days integer NOT NULL DEFAULT 30,
  max_validity_days integer NOT NULL DEFAULT 365,
  requires_photo boolean NOT NULL DEFAULT false,
  requires_id_document boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT security_contact_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.security_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resident_id uuid NOT NULL,
  category_id uuid NOT NULL,
  full_name text NOT NULL,
  phone_primary text NOT NULL,
  phone_secondary text,
  photo_url text,
  id_type USER-DEFINED,
  id_number text,
  id_document_url text,
  address text,
  next_of_kin_name text,
  next_of_kin_phone text,
  employer text,
  relationship text,
  notes text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::security_contact_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT security_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT security_contacts_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id),
  CONSTRAINT security_contacts_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.security_contact_categories(id),
  CONSTRAINT security_contacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.streets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  short_name character varying,
  CONSTRAINT streets_pkey PRIMARY KEY (id),
  CONSTRAINT streets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  value jsonb NOT NULL,
  description text,
  category text DEFAULT 'general'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transaction_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['credit'::text, 'debit'::text])),
  description text,
  color text DEFAULT 'gray'::text,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  keywords ARRAY DEFAULT '{}'::text[],
  CONSTRAINT transaction_tags_pkey PRIMARY KEY (id)
);
CREATE TABLE public.verification_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  resident_id uuid NOT NULL,
  token_type USER-DEFINED NOT NULL,
  token character NOT NULL CHECK (token ~ '^[0-9]{6}$'::text),
  target_value text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  used_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT verification_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT verification_tokens_resident_id_fkey FOREIGN KEY (resident_id) REFERENCES public.residents(id)
);
CREATE TABLE public.wallet_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  wallet_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  amount numeric NOT NULL,
  balance_after numeric NOT NULL,
  reference_type text,
  reference_id uuid,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wallet_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT wallet_transactions_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.resident_wallets(id)
);