import { Document, Page, Text, View } from '@react-pdf/renderer';
import { reportPdfStyles as s } from '@/lib/pdf/reports/base-styles';
import { formatCurrency, formatDate } from '@/lib/utils';
import type { CollectionReportData } from '@/actions/reports/report-engine';

export function CollectionReportPdf({ data }: { data: CollectionReportData }) {
  const { summary, byResident } = data;

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View style={s.headerRow}>
            <View>
              <Text style={s.headerTitle}>Collection Report</Text>
              <Text style={s.headerSubtitle}>Payment collection performance</Text>
            </View>
            <View style={s.headerRight}>
              <Text style={s.headerRightTitle}>Residio</Text>
              <Text style={s.headerRightDate}>{formatDate(new Date())}</Text>
            </View>
          </View>
        </View>

        <View style={s.section}>
          <Text style={s.sectionTitle}>Summary</Text>
          <View style={s.summaryRow}>
            <View style={s.summaryBox}>
              <Text style={s.summaryLabel}>Collection Rate</Text>
              <Text style={[s.summaryValue]}>{summary.collectionRate.toFixed(1)}%</Text>
            </View>
            <View style={s.summaryBox}>
              <Text style={s.summaryLabel}>Invoiced</Text>
              <Text style={[s.summaryValue]}>{formatCurrency(summary.totalInvoiced)}</Text>
            </View>
            <View style={s.summaryBox}>
              <Text style={s.summaryLabel}>Collected</Text>
              <Text style={[s.summaryValue, s.amountPositive]}>{formatCurrency(summary.totalCollected)}</Text>
            </View>
            <View style={s.summaryBox}>
              <Text style={s.summaryLabel}>Outstanding</Text>
              <Text style={[s.summaryValue, s.amountNegative]}>{formatCurrency(summary.totalOutstanding)}</Text>
            </View>
          </View>
        </View>

        <View style={s.section}>
          <Text style={s.sectionTitle}>By Resident ({byResident.length})</Text>
          <View style={s.table}>
            <View style={s.tableHeader}>
              <Text style={[s.tableHeaderCell, { flex: 3 }]}>Resident</Text>
              <Text style={[s.tableHeaderCell, { flex: 2 }]}>House</Text>
              <Text style={[s.tableHeaderCell, s.amountRight, { flex: 2 }]}>Invoiced</Text>
              <Text style={[s.tableHeaderCell, s.amountRight, { flex: 2 }]}>Paid</Text>
              <Text style={[s.tableHeaderCell, s.amountRight, { flex: 2 }]}>Balance</Text>
            </View>
            {byResident.map((r, i) => (
              <View key={i} style={[s.tableRow, i % 2 === 1 ? s.tableRowAlt : {}]}>
                <Text style={[s.tableCell, { flex: 3 }]}>{r.residentName}</Text>
                <Text style={[s.tableCell, { flex: 2 }]}>{r.houseNumber}</Text>
                <Text style={[s.tableCell, s.amountRight, { flex: 2 }]}>{formatCurrency(r.totalInvoiced)}</Text>
                <Text style={[s.tableCell, s.amountRight, { flex: 2 }]}>{formatCurrency(r.totalPaid)}</Text>
                <Text style={[s.tableCell, s.amountRight, { flex: 2 }, r.outstanding > 0 ? s.amountNegative : s.amountPositive]}>{formatCurrency(r.outstanding)}</Text>
              </View>
            ))}
          </View>
        </View>

        <Text style={s.footer}>Generated by Residio — Collection Report</Text>
      </Page>
    </Document>
  );
}
