import { Document, Page, Text, View } from '@react-pdf/renderer';
import { reportPdfStyles as s } from '@/lib/pdf/reports/base-styles';
import { formatCurrency, formatDate } from '@/lib/utils';
import type { InvoiceAgingData } from '@/actions/reports/report-engine';

export function InvoiceAgingPdf({ data }: { data: InvoiceAgingData }) {
  const { summary, byBracket } = data;

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View style={s.headerRow}>
            <View>
              <Text style={s.headerTitle}>Invoice Aging Report</Text>
              <Text style={s.headerSubtitle}>Outstanding invoices by days overdue</Text>
            </View>
            <View style={s.headerRight}>
              <Text style={s.headerRightTitle}>Residio</Text>
              <Text style={s.headerRightDate}>{formatDate(new Date())}</Text>
            </View>
          </View>
        </View>

        <View style={s.section}>
          <Text style={s.sectionTitle}>Aging Summary</Text>
          <View style={s.summaryRow}>
            {[
              { label: 'Current (0-30d)', value: summary.current },
              { label: '30-60 Days', value: summary.days30to60 },
              { label: '60-90 Days', value: summary.days60to90 },
              { label: 'Over 90 Days', value: summary.over90Days },
            ].map((bracket) => (
              <View key={bracket.label} style={s.summaryBox}>
                <Text style={s.summaryLabel}>{bracket.label}</Text>
                <Text style={[s.summaryValue, bracket.value > 0 ? s.amountNegative : {}]}>{formatCurrency(bracket.value)}</Text>
              </View>
            ))}
          </View>
        </View>

        {byBracket.map((bracket) => (
          <View key={bracket.bracket} style={s.section}>
            <Text style={s.sectionTitle}>{bracket.bracket} ({bracket.invoiceCount} invoices — {formatCurrency(bracket.totalAmount)})</Text>
            <View style={s.table}>
              <View style={s.tableHeader}>
                <Text style={[s.tableHeaderCell, { flex: 3 }]}>Invoice</Text>
                <Text style={[s.tableHeaderCell, { flex: 2 }]}>Resident</Text>
                <Text style={[s.tableHeaderCell, { flex: 2 }]}>Due Date</Text>
                <Text style={[s.tableHeaderCell, s.amountRight, { flex: 2 }]}>Amount</Text>
                <Text style={[s.tableHeaderCell, s.amountRight, { flex: 2 }]}>Outstanding</Text>
              </View>
              {bracket.invoices.map((inv, i) => (
                <View key={i} style={[s.tableRow, i % 2 === 1 ? s.tableRowAlt : {}]}>
                  <Text style={[s.tableCell, { flex: 3 }]}>{inv.invoiceNumber}</Text>
                  <Text style={[s.tableCell, { flex: 2 }]}>{inv.residentName}</Text>
                  <Text style={[s.tableCell, { flex: 2 }]}>{inv.dueDate}</Text>
                  <Text style={[s.tableCell, s.amountRight, { flex: 2 }]}>{formatCurrency(inv.amountDue)}</Text>
                  <Text style={[s.tableCell, s.amountRight, { flex: 2 }, inv.outstanding > 0 ? s.amountNegative : s.amountPositive]}>{formatCurrency(inv.outstanding)}</Text>
                </View>
              ))}
            </View>
          </View>
        ))}

        <Text style={s.footer}>Generated by Residio — Invoice Aging Report</Text>
      </Page>
    </Document>
  );
}
