import { Document, Page, Text, View } from '@react-pdf/renderer';
import { reportPdfStyles as s } from '@/lib/pdf/reports/base-styles';
import { formatCurrency, formatDate } from '@/lib/utils';
import type { TransactionLogData, DebtorsReportData, IndebtednessReportData, DevelopmentLevyData } from '@/actions/reports/report-engine';

export function TransactionLogPdf({ data }: { data: TransactionLogData }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View style={s.headerRow}>
            <View>
              <Text style={s.headerTitle}>Transaction Log</Text>
              <Text style={s.headerSubtitle}>{data.summary.totalTransactions} transactions</Text>
            </View>
            <View style={s.headerRight}>
              <Text style={s.headerRightTitle}>Residio</Text>
              <Text style={s.headerRightDate}>{formatDate(new Date())}</Text>
            </View>
          </View>
        </View>
        <View style={s.table}>
          <View style={s.tableHeader}>
            <Text style={[s.tableHeaderCell, { flex: 2 }]}>Date</Text>
            <Text style={[s.tableHeaderCell, { flex: 3 }]}>Description</Text>
            <Text style={[s.tableHeaderCell, { flex: 2 }]}>Category</Text>
            <Text style={[s.tableHeaderCell, s.amountRight, { flex: 2 }]}>Amount</Text>
            <Text style={[s.tableHeaderCell, { flex: 2 }]}>Type</Text>
          </View>
          {data.transactions.map((tx, i) => (
            <View key={i} style={[s.tableRow, i % 2 === 1 && s.tableRowAlt]}>
              <Text style={[s.tableCell, { flex: 2 }]}>{tx.date}</Text>
              <Text style={[s.tableCell, { flex: 3 }]}>{tx.description}</Text>
              <Text style={[s.tableCell, { flex: 2 }]}>{tx.category || '-'}</Text>
              <Text style={[s.tableCell, s.amountRight, { flex: 2 }, tx.type === 'credit' ? s.amountPositive : s.amountNegative]}>{formatCurrency(tx.amount)}</Text>
              <Text style={[s.tableCell, { flex: 2 }]}>{tx.type}</Text>
            </View>
          ))}
        </View>
        <Text style={s.footer}>Generated by Residio — Transaction Log</Text>
      </Page>
    </Document>
  );
}

export function DebtorsReportPdf({ data }: { data: DebtorsReportData }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View style={s.headerRow}>
            <View><Text style={s.headerTitle}>Debtors Report</Text></View>
            <View style={s.headerRight}><Text style={s.headerRightTitle}>Residio</Text><Text style={s.headerRightDate}>{formatDate(new Date())}</Text></View>
          </View>
        </View>
        <View style={s.section}>
          <View style={s.summaryRow}>
            <View style={s.summaryBox}><Text style={s.summaryLabel}>Total Debtors</Text><Text style={s.summaryValue}>{data.summary.totalDebtors}</Text></View>
            <View style={s.summaryBox}><Text style={s.summaryLabel}>Outstanding</Text><Text style={[s.summaryValue, s.amountNegative]}>{formatCurrency(data.summary.totalOutstanding)}</Text></View>
            <View style={s.summaryBox}><Text style={s.summaryLabel}>Avg Days Overdue</Text><Text style={s.summaryValue}>{data.summary.averageDaysOverdue}</Text></View>
          </View>
        </View>
        <View style={s.table}>
          <View style={s.tableHeader}>
            <Text style={[s.tableHeaderCell, { flex: 3 }]}>Debtor</Text>
            <Text style={[s.tableHeaderCell, { flex: 2 }]}>House</Text>
            <Text style={[s.tableHeaderCell, s.amountRight, { flex: 2 }]}>Outstanding</Text>
            <Text style={[s.tableHeaderCell, s.amountRight, { flex: 2 }]}>Over 90d</Text>
            <Text style={[s.tableHeaderCell, { flex: 2 }]}>Contact</Text>
          </View>
          {data.debtors.map((d, i) => (
            <View key={i} style={[s.tableRow, i % 2 === 1 && s.tableRowAlt]}>
              <Text style={[s.tableCell, { flex: 3 }]}>{d.residentName}</Text>
              <Text style={[s.tableCell, { flex: 2 }]}>{d.houseNumber}</Text>
              <Text style={[s.tableCell, s.amountRight, { flex: 2 }, s.amountNegative]}>{formatCurrency(d.totalOutstanding)}</Text>
              <Text style={[s.tableCell, s.amountRight, { flex: 2 }, s.amountNegative]}>{formatCurrency(d.over90Days)}</Text>
              <Text style={[s.tableCell, { flex: 2 }]}>{d.phonePrimary || d.phoneSecondary || '-'}</Text>
            </View>
          ))}
        </View>
        <Text style={s.footer}>Generated by Residio — Debtors Report</Text>
      </Page>
    </Document>
  );
}

export function IndebtednessReportPdf({ data }: { data: IndebtednessReportData }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View style={s.headerRow}>
            <View><Text style={s.headerTitle}>Indebtedness Report</Text></View>
            <View style={s.headerRight}><Text style={s.headerRightTitle}>Residio</Text><Text style={s.headerRightDate}>{formatDate(new Date())}</Text></View>
          </View>
        </View>
        <View style={s.table}>
          <View style={s.tableHeader}>
            <Text style={[s.tableHeaderCell, { flex: 2 }]}>House</Text>
            <Text style={[s.tableHeaderCell, { flex: 2 }]}>Street</Text>
            <Text style={[s.tableHeaderCell, { flex: 3 }]}>Resident</Text>
            <Text style={[s.tableHeaderCell, { flex: 2 }]}>Indebted</Text>
            {typeof data.houses[0]?.outstandingAmount === 'number' && <Text style={[s.tableHeaderCell, s.amountRight, { flex: 2 }]}>Amount</Text>}
          </View>
          {data.houses.map((h, i) => (
            <View key={i} style={[s.tableRow, i % 2 === 1 && s.tableRowAlt]}>
              <Text style={[s.tableCell, { flex: 2 }]}>{h.houseNumber}</Text>
              <Text style={[s.tableCell, { flex: 2 }]}>{h.streetName}</Text>
              <Text style={[s.tableCell, { flex: 3 }]}>{h.primaryResidentName || 'Vacant'}</Text>
              <Text style={[s.tableCell, { flex: 2 }, h.isIndebted ? s.amountNegative : s.amountPositive]}>{h.isIndebted ? 'Yes' : 'No'}</Text>
              {typeof h.outstandingAmount === 'number' && <Text style={[s.tableCell, s.amountRight, { flex: 2 }, {}]}>{formatCurrency(h.outstandingAmount || 0)}</Text>}
            </View>
          ))}
        </View>
        <Text style={s.footer}>Generated by Residio — Indebtedness Report</Text>
      </Page>
    </Document>
  );
}

export function DevelopmentLevyPdf({ data }: { data: DevelopmentLevyData }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View style={s.headerRow}>
            <View><Text style={s.headerTitle}>Development Levy Report</Text></View>
            <View style={s.headerRight}><Text style={s.headerRightTitle}>Residio</Text><Text style={s.headerRightDate}>{formatDate(new Date())}</Text></View>
          </View>
        </View>
        <View style={s.section}>
          <View style={s.summaryRow}>
            <View style={s.summaryBox}><Text style={s.summaryLabel}>Total Houses</Text><Text style={s.summaryValue}>{data.summary.totalHouses}</Text></View>
            <View style={s.summaryBox}><Text style={s.summaryLabel}>Collected</Text><Text style={[s.summaryValue, s.amountPositive]}>{formatCurrency(data.summary.collectedAmount)}</Text></View>
            <View style={s.summaryBox}><Text style={s.summaryLabel}>Pending</Text><Text style={[s.summaryValue, s.amountNegative]}>{formatCurrency(data.summary.totalAmount - data.summary.collectedAmount)}</Text></View>
          </View>
        </View>
        <View style={s.table}>
          <View style={s.tableHeader}>
            <Text style={[s.tableHeaderCell, { flex: 2 }]}>House</Text>
            <Text style={[s.tableHeaderCell, { flex: 3 }]}>Responsible</Text>
            <Text style={[s.tableHeaderCell, s.amountRight, { flex: 2 }]}>Amount</Text>
            <Text style={[s.tableHeaderCell, { flex: 2 }]}>Status</Text>
          </View>
          {data.houses.map((h, i) => (
            <View key={i} style={[s.tableRow, i % 2 === 1 && s.tableRowAlt]}>
              <Text style={[s.tableCell, { flex: 2 }]}>{h.houseNumber}</Text>
              <Text style={[s.tableCell, { flex: 3 }]}>{h.responsibleResidentName}</Text>
              <Text style={[s.tableCell, s.amountRight, { flex: 2 }]}>{formatCurrency(h.levyAmount)}</Text>
              <Text style={[s.tableCell, { flex: 2 }, h.isPaid ? s.amountPositive : s.amountNegative]}>{h.isPaid ? 'Paid' : 'Unpaid'}</Text>
            </View>
          ))}
        </View>
        <Text style={s.footer}>Generated by Residio — Development Levy Report</Text>
      </Page>
    </Document>
  );
}
