'use server';

import { createServerSupabaseClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';
import type { Resident } from '@/types/database';
import type { CreateResidentData } from '@/lib/validators/resident';

export interface CreateResidentResponse {
  data: Resident | null;
  error: string | null;
}

export async function createResident(formData: CreateResidentData): Promise<CreateResidentResponse> {
  const supabase = await createServerSupabaseClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { data: null, error: 'Unauthorized' };
  }

  // Create resident (resident_code is auto-generated by trigger)
  const { data: resident, error: residentError } = await supabase
    .from('residents')
    .insert({
      first_name: formData.first_name,
      last_name: formData.last_name,
      email: formData.email || null,
      phone_primary: formData.phone_primary,
      phone_secondary: formData.phone_secondary || null,
      resident_type: formData.resident_type,
      emergency_contact_name: formData.emergency_contact_name || null,
      emergency_contact_phone: formData.emergency_contact_phone || null,
      emergency_contact_relationship: formData.emergency_contact_relationship || null,
      notes: formData.notes || null,
      created_by: user.id,
      updated_by: user.id,
    })
    .select()
    .single();

  if (residentError) {
    return { data: null, error: residentError.message };
  }

  // Create house assignment if provided
  if (formData.house_id && formData.resident_role) {
    const { error: assignmentError } = await supabase
      .from('resident_houses')
      .insert({
        resident_id: resident.id,
        house_id: formData.house_id,
        resident_role: formData.resident_role,
        is_primary: true,
        move_in_date: formData.move_in_date || new Date().toISOString().split('T')[0],
        created_by: user.id,
      });

    if (assignmentError) {
      // Rollback: delete resident if house assignment fails
      await supabase.from('residents').delete().eq('id', resident.id);
      return { data: null, error: `Failed to assign house: ${assignmentError.message}` };
    }
  }

  revalidatePath('/residents');
  revalidatePath('/houses');
  return { data: resident, error: null };
}
