name: Auto Add Issues to Project

on:
  issues:
    types: [opened, edited]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add Issue to Project
        uses: actions/add-to-project@v1.0.2
        with:
          # The full URL of your GitHub Project (Projects v2)
          project-url: https://github.com/orgs/Meggarminds/projects/3/views/1
          
          # A Personal Access Token (PAT) or GitHub App Token with project write permissions
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
